// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package db

import (
	"context"
	"time"
)

const consumeAgentRegistrationToken = `-- name: ConsumeAgentRegistrationToken :one
UPDATE agent_registration_tokens
SET consumed_at = now()
WHERE token_hash = $1 AND consumed_at IS NULL AND expires_at > now()
RETURNING id, server_id, workspace_id
`

type ConsumeAgentRegistrationTokenRow struct {
	ID          string
	ServerID    string
	WorkspaceID string
}

// ConsumeAgentRegistrationToken atomically validates and consumes a one-time token by
// its hash. The WHERE clause enforces single use and expiry, so a replay returns no rows.
func (q *Queries) ConsumeAgentRegistrationToken(ctx context.Context, tokenHash []byte) (ConsumeAgentRegistrationTokenRow, error) {
	row := q.db.QueryRow(ctx, consumeAgentRegistrationToken, tokenHash)
	var i ConsumeAgentRegistrationTokenRow
	err := row.Scan(&i.ID, &i.ServerID, &i.WorkspaceID)
	return i, err
}

const createAgentRegistrationToken = `-- name: CreateAgentRegistrationToken :one
INSERT INTO agent_registration_tokens (server_id, workspace_id, token_hash, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, server_id, workspace_id, created_at, expires_at, consumed_at
`

type CreateAgentRegistrationTokenParams struct {
	ServerID    string
	WorkspaceID string
	TokenHash   []byte
	CreatedBy   string
	ExpiresAt   time.Time
}

type CreateAgentRegistrationTokenRow struct {
	ID          string
	ServerID    string
	WorkspaceID string
	CreatedAt   time.Time
	ExpiresAt   time.Time
	ConsumedAt  *time.Time
}

func (q *Queries) CreateAgentRegistrationToken(ctx context.Context, arg CreateAgentRegistrationTokenParams) (CreateAgentRegistrationTokenRow, error) {
	row := q.db.QueryRow(ctx, createAgentRegistrationToken,
		arg.ServerID,
		arg.WorkspaceID,
		arg.TokenHash,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i CreateAgentRegistrationTokenRow
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.WorkspaceID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const getServerWorkspace = `-- name: GetServerWorkspace :one
SELECT workspace_id FROM servers WHERE id = $1
`

// GetServerWorkspace resolves a server's owning workspace so agent actions authorize
// against it WITHOUT importing the servers module (see modules.md Rule 4: an ancestor
// lookup from postgres.go is exactly what Rule 2 permits).
func (q *Queries) GetServerWorkspace(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getServerWorkspace, id)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const heartbeatAgent = `-- name: HeartbeatAgent :one
UPDATE agents
SET last_seen_at        = now(),
    agent_version       = $2,
    docker_available    = $3,
    docker_version      = $4,
    os                  = $5,
    arch                = $6,
    caddy_available     = $7,
    caddy_running       = $8,
    caddy_version       = $9,
    disk_total_bytes    = $10,
    disk_free_bytes     = $11,
    mem_total_bytes     = $12,
    mem_available_bytes = $13,
    cpu_count           = $14
WHERE credential_hash = $1
RETURNING id, server_id, workspace_id, agent_version, docker_available, docker_version, os, arch, caddy_available, caddy_running, caddy_version, disk_total_bytes, disk_free_bytes, mem_total_bytes, mem_available_bytes, cpu_count, last_seen_at, created_at
`

type HeartbeatAgentParams struct {
	CredentialHash    []byte
	AgentVersion      string
	DockerAvailable   *bool
	DockerVersion     string
	Os                string
	Arch              string
	CaddyAvailable    *bool
	CaddyRunning      bool
	CaddyVersion      string
	DiskTotalBytes    int64
	DiskFreeBytes     int64
	MemTotalBytes     int64
	MemAvailableBytes int64
	CpuCount          int32
}

type HeartbeatAgentRow struct {
	ID                string
	ServerID          string
	WorkspaceID       string
	AgentVersion      string
	DockerAvailable   *bool
	DockerVersion     string
	Os                string
	Arch              string
	CaddyAvailable    *bool
	CaddyRunning      bool
	CaddyVersion      string
	DiskTotalBytes    int64
	DiskFreeBytes     int64
	MemTotalBytes     int64
	MemAvailableBytes int64
	CpuCount          int32
	LastSeenAt        *time.Time
	CreatedAt         time.Time
}

// HeartbeatAgent validates the durable credential by its hash AND records liveness plus
// the latest compatibility facts in one statement (see UseAPIToken in auth.sql). Returns
// the agent when the hash matches.
func (q *Queries) HeartbeatAgent(ctx context.Context, arg HeartbeatAgentParams) (HeartbeatAgentRow, error) {
	row := q.db.QueryRow(ctx, heartbeatAgent,
		arg.CredentialHash,
		arg.AgentVersion,
		arg.DockerAvailable,
		arg.DockerVersion,
		arg.Os,
		arg.Arch,
		arg.CaddyAvailable,
		arg.CaddyRunning,
		arg.CaddyVersion,
		arg.DiskTotalBytes,
		arg.DiskFreeBytes,
		arg.MemTotalBytes,
		arg.MemAvailableBytes,
		arg.CpuCount,
	)
	var i HeartbeatAgentRow
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.WorkspaceID,
		&i.AgentVersion,
		&i.DockerAvailable,
		&i.DockerVersion,
		&i.Os,
		&i.Arch,
		&i.CaddyAvailable,
		&i.CaddyRunning,
		&i.CaddyVersion,
		&i.DiskTotalBytes,
		&i.DiskFreeBytes,
		&i.MemTotalBytes,
		&i.MemAvailableBytes,
		&i.CpuCount,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentsByWorkspace = `-- name: ListAgentsByWorkspace :many
SELECT id, server_id, workspace_id, agent_version, docker_available, docker_version, os, arch, caddy_available, caddy_running, caddy_version, disk_total_bytes, disk_free_bytes, mem_total_bytes, mem_available_bytes, cpu_count, last_seen_at, created_at
FROM agents
WHERE workspace_id = $1
ORDER BY created_at DESC
`

type ListAgentsByWorkspaceRow struct {
	ID                string
	ServerID          string
	WorkspaceID       string
	AgentVersion      string
	DockerAvailable   *bool
	DockerVersion     string
	Os                string
	Arch              string
	CaddyAvailable    *bool
	CaddyRunning      bool
	CaddyVersion      string
	DiskTotalBytes    int64
	DiskFreeBytes     int64
	MemTotalBytes     int64
	MemAvailableBytes int64
	CpuCount          int32
	LastSeenAt        *time.Time
	CreatedAt         time.Time
}

func (q *Queries) ListAgentsByWorkspace(ctx context.Context, workspaceID string) ([]ListAgentsByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listAgentsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentsByWorkspaceRow{}
	for rows.Next() {
		var i ListAgentsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.WorkspaceID,
			&i.AgentVersion,
			&i.DockerAvailable,
			&i.DockerVersion,
			&i.Os,
			&i.Arch,
			&i.CaddyAvailable,
			&i.CaddyRunning,
			&i.CaddyVersion,
			&i.DiskTotalBytes,
			&i.DiskFreeBytes,
			&i.MemTotalBytes,
			&i.MemAvailableBytes,
			&i.CpuCount,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgent = `-- name: UpsertAgent :one
INSERT INTO agents (server_id, workspace_id, public_key, credential_hash, agent_version)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (server_id) DO UPDATE
    SET public_key       = EXCLUDED.public_key,
        credential_hash  = EXCLUDED.credential_hash,
        agent_version    = EXCLUDED.agent_version,
        last_seen_at     = NULL,
        docker_available = NULL,
        docker_version   = '',
        os               = '',
        arch             = ''
RETURNING id, server_id, workspace_id, agent_version, docker_available, docker_version, os, arch, last_seen_at, created_at
`

type UpsertAgentParams struct {
	ServerID       string
	WorkspaceID    string
	PublicKey      []byte
	CredentialHash []byte
	AgentVersion   string
}

type UpsertAgentRow struct {
	ID              string
	ServerID        string
	WorkspaceID     string
	AgentVersion    string
	DockerAvailable *bool
	DockerVersion   string
	Os              string
	Arch            string
	LastSeenAt      *time.Time
	CreatedAt       time.Time
}

// UpsertAgent registers (or re-registers) the single agent for a server. A reinstall
// rotates the public key and credential and clears the last heartbeat and reported health
// facts, so a re-connected server starts from "unknown" until its first beat.
func (q *Queries) UpsertAgent(ctx context.Context, arg UpsertAgentParams) (UpsertAgentRow, error) {
	row := q.db.QueryRow(ctx, upsertAgent,
		arg.ServerID,
		arg.WorkspaceID,
		arg.PublicKey,
		arg.CredentialHash,
		arg.AgentVersion,
	)
	var i UpsertAgentRow
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.WorkspaceID,
		&i.AgentVersion,
		&i.DockerAvailable,
		&i.DockerVersion,
		&i.Os,
		&i.Arch,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}
