// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
)

const createAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO audit_events (workspace_id, actor, action, target_type, target_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, actor, action, target_type, target_id, created_at
`

type CreateAuditEventParams struct {
	WorkspaceID *string
	Actor       string
	Action      string
	TargetType  string
	TargetID    string
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, createAuditEvent,
		arg.WorkspaceID,
		arg.Actor,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Actor,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.CreatedAt,
	)
	return i, err
}
