// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backups.sql

package db

import (
	"context"
)

const claimNextBackupForServer = `-- name: ClaimNextBackupForServer :one
UPDATE backups
SET status = 'assigned', updated_at = now()
WHERE id = (
    SELECT b.id FROM backups b
    WHERE b.server_id = $1 AND b.status = 'queued'
    ORDER BY b.created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, service_id, environment_id, project_id, workspace_id, server_id, destination, artifact_uri, size_bytes, checksum, status, message, error, created_at, updated_at, label, trigger_source
`

// ClaimNextBackupForServer atomically claims the oldest queued backup for a server, flipping it
// to 'assigned' so concurrent polls never grab the same one (cf. ClaimNextDeploymentForServer).
func (q *Queries) ClaimNextBackupForServer(ctx context.Context, serverID string) (Backup, error) {
	row := q.db.QueryRow(ctx, claimNextBackupForServer, serverID)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.Destination,
		&i.ArtifactUri,
		&i.SizeBytes,
		&i.Checksum,
		&i.Status,
		&i.Message,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Label,
		&i.TriggerSource,
	)
	return i, err
}

const claimNextRestoreForServer = `-- name: ClaimNextRestoreForServer :one
UPDATE restore_jobs
SET status = 'assigned', updated_at = now()
WHERE id = (
    SELECT r.id FROM restore_jobs r
    WHERE r.server_id = $1 AND r.status = 'queued'
    ORDER BY r.created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, backup_id, service_id, environment_id, project_id, workspace_id, server_id, artifact_uri, status, message, error, created_at, updated_at
`

// ClaimNextRestoreForServer atomically claims the oldest queued restore for a server (cf.
// ClaimNextBackupForServer).
func (q *Queries) ClaimNextRestoreForServer(ctx context.Context, serverID string) (RestoreJob, error) {
	row := q.db.QueryRow(ctx, claimNextRestoreForServer, serverID)
	var i RestoreJob
	err := row.Scan(
		&i.ID,
		&i.BackupID,
		&i.ServiceID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.ArtifactUri,
		&i.Status,
		&i.Message,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countBackupsForService = `-- name: CountBackupsForService :one
SELECT count(*) FROM backups WHERE service_id = $1 AND status = 'succeeded'
`

func (q *Queries) CountBackupsForService(ctx context.Context, serviceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countBackupsForService, serviceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBackup = `-- name: CreateBackup :one

INSERT INTO backups (service_id, environment_id, project_id, workspace_id, server_id, label, trigger_source)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, service_id, environment_id, project_id, workspace_id, server_id, destination, artifact_uri, size_bytes, checksum, status, message, error, created_at, updated_at, label, trigger_source
`

type CreateBackupParams struct {
	ServiceID     string
	EnvironmentID string
	ProjectID     string
	WorkspaceID   string
	ServerID      string
	Label         string
	TriggerSource string
}

// Queries for the backups module (internal/backups). The agent claim mirrors the deployment
// claim (single-statement FOR UPDATE SKIP LOCKED). Credential resolution and config reads reuse
// the existing GetAgentServerByCredential / ListConfigForService queries.
func (q *Queries) CreateBackup(ctx context.Context, arg CreateBackupParams) (Backup, error) {
	row := q.db.QueryRow(ctx, createBackup,
		arg.ServiceID,
		arg.EnvironmentID,
		arg.ProjectID,
		arg.WorkspaceID,
		arg.ServerID,
		arg.Label,
		arg.TriggerSource,
	)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.Destination,
		&i.ArtifactUri,
		&i.SizeBytes,
		&i.Checksum,
		&i.Status,
		&i.Message,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Label,
		&i.TriggerSource,
	)
	return i, err
}

const createRestoreJob = `-- name: CreateRestoreJob :one

INSERT INTO restore_jobs (backup_id, service_id, environment_id, project_id, workspace_id, server_id, artifact_uri)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, backup_id, service_id, environment_id, project_id, workspace_id, server_id, artifact_uri, status, message, error, created_at, updated_at
`

type CreateRestoreJobParams struct {
	BackupID      string
	ServiceID     string
	EnvironmentID string
	ProjectID     string
	WorkspaceID   string
	ServerID      string
	ArtifactUri   string
}

// --- restore_jobs ---
func (q *Queries) CreateRestoreJob(ctx context.Context, arg CreateRestoreJobParams) (RestoreJob, error) {
	row := q.db.QueryRow(ctx, createRestoreJob,
		arg.BackupID,
		arg.ServiceID,
		arg.EnvironmentID,
		arg.ProjectID,
		arg.WorkspaceID,
		arg.ServerID,
		arg.ArtifactUri,
	)
	var i RestoreJob
	err := row.Scan(
		&i.ID,
		&i.BackupID,
		&i.ServiceID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.ArtifactUri,
		&i.Status,
		&i.Message,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBackup = `-- name: GetBackup :one
SELECT id, service_id, environment_id, project_id, workspace_id, server_id, destination, artifact_uri, size_bytes, checksum, status, message, error, created_at, updated_at, label, trigger_source FROM backups WHERE id = $1
`

func (q *Queries) GetBackup(ctx context.Context, id string) (Backup, error) {
	row := q.db.QueryRow(ctx, getBackup, id)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.Destination,
		&i.ArtifactUri,
		&i.SizeBytes,
		&i.Checksum,
		&i.Status,
		&i.Message,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Label,
		&i.TriggerSource,
	)
	return i, err
}

const getBackupServiceTarget = `-- name: GetBackupServiceTarget :one
SELECT id, name, environment_id, project_id, workspace_id, source_kind, template_id
FROM services WHERE id = $1
`

type GetBackupServiceTargetRow struct {
	ID            string
	Name          string
	EnvironmentID string
	ProjectID     string
	WorkspaceID   string
	SourceKind    string
	TemplateID    string
}

// GetBackupServiceTarget resolves the database service a backup targets: its denormalized
// workspace/project/environment, its name, and its source/template kind (so the module can
// confirm it is a managed Postgres template before backing it up).
func (q *Queries) GetBackupServiceTarget(ctx context.Context, id string) (GetBackupServiceTargetRow, error) {
	row := q.db.QueryRow(ctx, getBackupServiceTarget, id)
	var i GetBackupServiceTargetRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.SourceKind,
		&i.TemplateID,
	)
	return i, err
}

const getLatestRunningServerForService = `-- name: GetLatestRunningServerForService :one
SELECT server_id FROM deployments
WHERE service_id = $1 AND status = 'running'
ORDER BY created_at DESC
LIMIT 1
`

// GetLatestRunningServerForService returns the server the service's current (running) container
// is on — the backup must run on that server's agent.
func (q *Queries) GetLatestRunningServerForService(ctx context.Context, serviceID string) (string, error) {
	row := q.db.QueryRow(ctx, getLatestRunningServerForService, serviceID)
	var server_id string
	err := row.Scan(&server_id)
	return server_id, err
}

const getRestoreJob = `-- name: GetRestoreJob :one
SELECT id, backup_id, service_id, environment_id, project_id, workspace_id, server_id, artifact_uri, status, message, error, created_at, updated_at FROM restore_jobs WHERE id = $1
`

func (q *Queries) GetRestoreJob(ctx context.Context, id string) (RestoreJob, error) {
	row := q.db.QueryRow(ctx, getRestoreJob, id)
	var i RestoreJob
	err := row.Scan(
		&i.ID,
		&i.BackupID,
		&i.ServiceID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.ArtifactUri,
		&i.Status,
		&i.Message,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBackupsByService = `-- name: ListBackupsByService :many
SELECT id, service_id, environment_id, project_id, workspace_id, server_id, destination, artifact_uri, size_bytes, checksum, status, message, error, created_at, updated_at, label, trigger_source FROM backups WHERE service_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListBackupsByService(ctx context.Context, serviceID string) ([]Backup, error) {
	rows, err := q.db.Query(ctx, listBackupsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Backup{}
	for rows.Next() {
		var i Backup
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.EnvironmentID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.ServerID,
			&i.Destination,
			&i.ArtifactUri,
			&i.SizeBytes,
			&i.Checksum,
			&i.Status,
			&i.Message,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Label,
			&i.TriggerSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRestoreJobsByService = `-- name: ListRestoreJobsByService :many
SELECT id, backup_id, service_id, environment_id, project_id, workspace_id, server_id, artifact_uri, status, message, error, created_at, updated_at FROM restore_jobs WHERE service_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListRestoreJobsByService(ctx context.Context, serviceID string) ([]RestoreJob, error) {
	rows, err := q.db.Query(ctx, listRestoreJobsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RestoreJob{}
	for rows.Next() {
		var i RestoreJob
		if err := rows.Scan(
			&i.ID,
			&i.BackupID,
			&i.ServiceID,
			&i.EnvironmentID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.ServerID,
			&i.ArtifactUri,
			&i.Status,
			&i.Message,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBackupStatus = `-- name: UpdateBackupStatus :one
UPDATE backups
SET status = $1,
    message = CASE WHEN $2::text <> '' THEN $2::text ELSE message END,
    error = CASE WHEN $3::text <> '' THEN $3::text ELSE error END,
    artifact_uri = CASE WHEN $4::text <> '' THEN $4::text ELSE artifact_uri END,
    size_bytes = CASE WHEN $5::bigint > 0 THEN $5::bigint ELSE size_bytes END,
    checksum = CASE WHEN $6::text <> '' THEN $6::text ELSE checksum END,
    updated_at = now()
WHERE id = $7
RETURNING id, service_id, environment_id, project_id, workspace_id, server_id, destination, artifact_uri, size_bytes, checksum, status, message, error, created_at, updated_at, label, trigger_source
`

type UpdateBackupStatusParams struct {
	Status      string
	Message     string
	Error       string
	ArtifactUri string
	SizeBytes   int64
	Checksum    string
	ID          string
}

// UpdateBackupStatus records a status transition. artifact_uri, size_bytes, checksum, message,
// and error are only known at certain points, so a zero/empty value never clobbers a set one.
func (q *Queries) UpdateBackupStatus(ctx context.Context, arg UpdateBackupStatusParams) (Backup, error) {
	row := q.db.QueryRow(ctx, updateBackupStatus,
		arg.Status,
		arg.Message,
		arg.Error,
		arg.ArtifactUri,
		arg.SizeBytes,
		arg.Checksum,
		arg.ID,
	)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.Destination,
		&i.ArtifactUri,
		&i.SizeBytes,
		&i.Checksum,
		&i.Status,
		&i.Message,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Label,
		&i.TriggerSource,
	)
	return i, err
}

const updateRestoreStatus = `-- name: UpdateRestoreStatus :one
UPDATE restore_jobs
SET status = $1,
    message = CASE WHEN $2::text <> '' THEN $2::text ELSE message END,
    error = CASE WHEN $3::text <> '' THEN $3::text ELSE error END,
    updated_at = now()
WHERE id = $4
RETURNING id, backup_id, service_id, environment_id, project_id, workspace_id, server_id, artifact_uri, status, message, error, created_at, updated_at
`

type UpdateRestoreStatusParams struct {
	Status  string
	Message string
	Error   string
	ID      string
}

func (q *Queries) UpdateRestoreStatus(ctx context.Context, arg UpdateRestoreStatusParams) (RestoreJob, error) {
	row := q.db.QueryRow(ctx, updateRestoreStatus,
		arg.Status,
		arg.Message,
		arg.Error,
		arg.ID,
	)
	var i RestoreJob
	err := row.Scan(
		&i.ID,
		&i.BackupID,
		&i.ServiceID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.ArtifactUri,
		&i.Status,
		&i.Message,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
