// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config.sql

package db

import (
	"context"
)

const deleteEnvironmentConfig = `-- name: DeleteEnvironmentConfig :one
DELETE FROM config_entries
WHERE environment_id = $1 AND key = $2
RETURNING id
`

type DeleteEnvironmentConfigParams struct {
	EnvironmentID *string
	Key           string
}

func (q *Queries) DeleteEnvironmentConfig(ctx context.Context, arg DeleteEnvironmentConfigParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteEnvironmentConfig, arg.EnvironmentID, arg.Key)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteServiceConfig = `-- name: DeleteServiceConfig :one
DELETE FROM config_entries
WHERE service_id = $1 AND key = $2
RETURNING id
`

type DeleteServiceConfigParams struct {
	ServiceID *string
	Key       string
}

// RETURNING id lets the caller tell a real delete from a no-op (no row -> ErrNoRows ->
// NotFound), so a delete that removed nothing is never audited as a change.
func (q *Queries) DeleteServiceConfig(ctx context.Context, arg DeleteServiceConfigParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteServiceConfig, arg.ServiceID, arg.Key)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getEnvironmentWorkspaceID = `-- name: GetEnvironmentWorkspaceID :one
SELECT p.workspace_id
FROM environments e
JOIN projects p ON p.id = e.project_id
WHERE e.id = $1
`

// Resolves an environment's owning workspace through its parent project, so the
// environment-scoped config path can authorize and audit against the workspace.
func (q *Queries) GetEnvironmentWorkspaceID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getEnvironmentWorkspaceID, id)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const getServiceWorkspaceID = `-- name: GetServiceWorkspaceID :one
SELECT workspace_id FROM services WHERE id = $1
`

// Resolves a service's owning workspace (denormalized onto the service row), so the
// service-scoped config path can authorize and audit against the workspace.
func (q *Queries) GetServiceWorkspaceID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getServiceWorkspaceID, id)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const listConfigForService = `-- name: ListConfigForService :many
SELECT id, type, scope, service_id, environment_id, key, value, ciphertext, created_at, updated_at FROM config_entries
WHERE service_id = $1
   OR environment_id = (SELECT environment_id FROM services WHERE id = $1)
ORDER BY scope, key
`

// Everything that applies to a service: its own service-level entries plus the
// environment-shared entries for the service's environment (resolved via the subquery).
// Ordered environment-first (scope ASC) so a single-pass merge lets service-level entries
// override environment-shared ones, then by key. Used by both the dashboard list and the
// deploy-time injection.
func (q *Queries) ListConfigForService(ctx context.Context, serviceID *string) ([]ConfigEntry, error) {
	rows, err := q.db.Query(ctx, listConfigForService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigEntry{}
	for rows.Next() {
		var i ConfigEntry
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Scope,
			&i.ServiceID,
			&i.EnvironmentID,
			&i.Key,
			&i.Value,
			&i.Ciphertext,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEnvironmentConfig = `-- name: UpsertEnvironmentConfig :one
INSERT INTO config_entries (type, scope, environment_id, key, value, ciphertext)
VALUES ($1, 'environment', $2, $3, $4, $5)
ON CONFLICT (environment_id, key) WHERE environment_id IS NOT NULL
DO UPDATE SET type = EXCLUDED.type, value = EXCLUDED.value, ciphertext = EXCLUDED.ciphertext, updated_at = now()
RETURNING id, type, scope, service_id, environment_id, key, value, ciphertext, created_at, updated_at
`

type UpsertEnvironmentConfigParams struct {
	Type          string
	EnvironmentID *string
	Key           string
	Value         *string
	Ciphertext    []byte
}

// Create-or-update an environment-scoped (shared) entry by (environment_id, key).
func (q *Queries) UpsertEnvironmentConfig(ctx context.Context, arg UpsertEnvironmentConfigParams) (ConfigEntry, error) {
	row := q.db.QueryRow(ctx, upsertEnvironmentConfig,
		arg.Type,
		arg.EnvironmentID,
		arg.Key,
		arg.Value,
		arg.Ciphertext,
	)
	var i ConfigEntry
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Scope,
		&i.ServiceID,
		&i.EnvironmentID,
		&i.Key,
		&i.Value,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertServiceConfig = `-- name: UpsertServiceConfig :one
INSERT INTO config_entries (type, scope, service_id, key, value, ciphertext)
VALUES ($1, 'service', $2, $3, $4, $5)
ON CONFLICT (service_id, key) WHERE service_id IS NOT NULL
DO UPDATE SET type = EXCLUDED.type, value = EXCLUDED.value, ciphertext = EXCLUDED.ciphertext, updated_at = now()
RETURNING id, type, scope, service_id, environment_id, key, value, ciphertext, created_at, updated_at
`

type UpsertServiceConfigParams struct {
	Type       string
	ServiceID  *string
	Key        string
	Value      *string
	Ciphertext []byte
}

// Create-or-update a service-scoped entry by (service_id, key). The conflict is the
// success path (config is mutable), so callers never see an AlreadyExists error. value is
// set for variables, ciphertext for secrets (the other is NULL). RETURNING yields the row
// for the audit target; the handler never returns a secret value over the wire.
func (q *Queries) UpsertServiceConfig(ctx context.Context, arg UpsertServiceConfigParams) (ConfigEntry, error) {
	row := q.db.QueryRow(ctx, upsertServiceConfig,
		arg.Type,
		arg.ServiceID,
		arg.Key,
		arg.Value,
		arg.Ciphertext,
	)
	var i ConfigEntry
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Scope,
		&i.ServiceID,
		&i.EnvironmentID,
		&i.Key,
		&i.Value,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
