// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package db

import (
	"context"
)

const appendDeploymentEvent = `-- name: AppendDeploymentEvent :one
INSERT INTO deployment_events (deployment_id, kind, status, message, stream)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, deployment_id, seq, kind, status, message, created_at, stream
`

type AppendDeploymentEventParams struct {
	DeploymentID string
	Kind         string
	Status       string
	Message      string
	Stream       string
}

func (q *Queries) AppendDeploymentEvent(ctx context.Context, arg AppendDeploymentEventParams) (DeploymentEvent, error) {
	row := q.db.QueryRow(ctx, appendDeploymentEvent,
		arg.DeploymentID,
		arg.Kind,
		arg.Status,
		arg.Message,
		arg.Stream,
	)
	var i DeploymentEvent
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.Seq,
		&i.Kind,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.Stream,
	)
	return i, err
}

const claimNextDeploymentForServer = `-- name: ClaimNextDeploymentForServer :one
UPDATE deployments
SET status = 'assigned', updated_at = now()
WHERE id = (
    SELECT d.id FROM deployments d
    WHERE d.server_id = $1 AND d.status = 'queued'
    ORDER BY d.created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at, source_kind, source_access, clone_url, git_ref, commit_sha, built_image_ref, route_url, service_id, rolled_back_from, kind, route_key, pr_number, pr_url
`

// ClaimNextDeploymentForServer atomically claims the oldest queued deployment for a
// server, flipping it to 'assigned' so concurrent polls (or a restart mid-deploy)
// never grab the same one. FOR UPDATE SKIP LOCKED + the single statement is the
// single-statement-claim pattern (cf. ConsumeAgentRegistrationToken in agents.sql).
func (q *Queries) ClaimNextDeploymentForServer(ctx context.Context, serverID string) (Deployment, error) {
	row := q.db.QueryRow(ctx, claimNextDeploymentForServer, serverID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.ImageRef,
		&i.ContainerPort,
		&i.HostPort,
		&i.ContainerID,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceKind,
		&i.SourceAccess,
		&i.CloneUrl,
		&i.GitRef,
		&i.CommitSha,
		&i.BuiltImageRef,
		&i.RouteUrl,
		&i.ServiceID,
		&i.RolledBackFrom,
		&i.Kind,
		&i.RouteKey,
		&i.PrNumber,
		&i.PrUrl,
	)
	return i, err
}

const claimNextTeardownForServer = `-- name: ClaimNextTeardownForServer :one
UPDATE teardown_jobs
SET status = 'assigned', updated_at = now()
WHERE id = (
    SELECT t.id FROM teardown_jobs t
    WHERE t.server_id = $1 AND t.status = 'queued'
    ORDER BY t.created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, deployment_id, service_id, route_key, environment_id, project_id, workspace_id, server_id, status, message, error, created_at, updated_at
`

// ClaimNextTeardownForServer atomically claims the oldest queued teardown for a server (cf.
// ClaimNextDeploymentForServer / ClaimNextRestoreForServer).
func (q *Queries) ClaimNextTeardownForServer(ctx context.Context, serverID string) (TeardownJob, error) {
	row := q.db.QueryRow(ctx, claimNextTeardownForServer, serverID)
	var i TeardownJob
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.ServiceID,
		&i.RouteKey,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.Status,
		&i.Message,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (service_id, route_key, environment_id, project_id, workspace_id, server_id, image_ref, container_port, rolled_back_from)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at, source_kind, source_access, clone_url, git_ref, commit_sha, built_image_ref, route_url, service_id, rolled_back_from, kind, route_key, pr_number, pr_url
`

type CreateDeploymentParams struct {
	ServiceID      string
	RouteKey       string
	EnvironmentID  string
	ProjectID      string
	WorkspaceID    string
	ServerID       string
	ImageRef       string
	ContainerPort  int32
	RolledBackFrom *string
}

// rolled_back_from is NULL for a normal deploy and set to the restored deployment's id when
// this row is a rollback (see RollbackDeployment). route_key = the service id for a production
// deployment, so its Caddy route, container-replacement group, and supersede scope are keyed
// by service exactly as before previews existed.
func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.ServiceID,
		arg.RouteKey,
		arg.EnvironmentID,
		arg.ProjectID,
		arg.WorkspaceID,
		arg.ServerID,
		arg.ImageRef,
		arg.ContainerPort,
		arg.RolledBackFrom,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.ImageRef,
		&i.ContainerPort,
		&i.HostPort,
		&i.ContainerID,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceKind,
		&i.SourceAccess,
		&i.CloneUrl,
		&i.GitRef,
		&i.CommitSha,
		&i.BuiltImageRef,
		&i.RouteUrl,
		&i.ServiceID,
		&i.RolledBackFrom,
		&i.Kind,
		&i.RouteKey,
		&i.PrNumber,
		&i.PrUrl,
	)
	return i, err
}

const createDeploymentFromGit = `-- name: CreateDeploymentFromGit :one
INSERT INTO deployments (
    service_id, route_key, environment_id, project_id, workspace_id, server_id,
    container_port, source_kind, source_access, clone_url, git_ref, rolled_back_from
)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'git', $8, $9, $10, $11)
RETURNING id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at, source_kind, source_access, clone_url, git_ref, commit_sha, built_image_ref, route_url, service_id, rolled_back_from, kind, route_key, pr_number, pr_url
`

type CreateDeploymentFromGitParams struct {
	ServiceID      string
	RouteKey       string
	EnvironmentID  string
	ProjectID      string
	WorkspaceID    string
	ServerID       string
	ContainerPort  int32
	SourceAccess   string
	CloneUrl       string
	GitRef         string
	RolledBackFrom *string
}

// CreateDeploymentFromGit records a queued deployment whose source is a repo+ref to clone
// and build on the server (image_ref is filled in by the agent after the build). route_key =
// the service id (a production deployment). See docs/architecture/deployment-engine.md.
func (q *Queries) CreateDeploymentFromGit(ctx context.Context, arg CreateDeploymentFromGitParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeploymentFromGit,
		arg.ServiceID,
		arg.RouteKey,
		arg.EnvironmentID,
		arg.ProjectID,
		arg.WorkspaceID,
		arg.ServerID,
		arg.ContainerPort,
		arg.SourceAccess,
		arg.CloneUrl,
		arg.GitRef,
		arg.RolledBackFrom,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.ImageRef,
		&i.ContainerPort,
		&i.HostPort,
		&i.ContainerID,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceKind,
		&i.SourceAccess,
		&i.CloneUrl,
		&i.GitRef,
		&i.CommitSha,
		&i.BuiltImageRef,
		&i.RouteUrl,
		&i.ServiceID,
		&i.RolledBackFrom,
		&i.Kind,
		&i.RouteKey,
		&i.PrNumber,
		&i.PrUrl,
	)
	return i, err
}

const createPreviewDeployment = `-- name: CreatePreviewDeployment :one
INSERT INTO deployments (
    service_id, route_key, kind, environment_id, project_id, workspace_id, server_id,
    container_port, source_kind, source_access, clone_url, git_ref, pr_number, pr_url
)
VALUES ($1, $2, 'preview', $3, $4, $5, $6, $7, 'git', $8, $9, $10, $11, $12)
RETURNING id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at, source_kind, source_access, clone_url, git_ref, commit_sha, built_image_ref, route_url, service_id, rolled_back_from, kind, route_key, pr_number, pr_url
`

type CreatePreviewDeploymentParams struct {
	ServiceID     string
	RouteKey      string
	EnvironmentID string
	ProjectID     string
	WorkspaceID   string
	ServerID      string
	ContainerPort int32
	SourceAccess  string
	CloneUrl      string
	GitRef        string
	PrNumber      int32
	PrUrl         string
}

// CreatePreviewDeployment records a queued PREVIEW deployment of a service: a build of a
// branch or pull-request head ref, isolated from the service's production deployment by its
// own route_key (which drives a distinct Caddy route, container-replacement group, and
// supersede scope). pr_number / pr_url link it to a GitHub pull request (0 / ” for a plain
// branch preview). Previews build PUBLIC git sources only in this slice.
func (q *Queries) CreatePreviewDeployment(ctx context.Context, arg CreatePreviewDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createPreviewDeployment,
		arg.ServiceID,
		arg.RouteKey,
		arg.EnvironmentID,
		arg.ProjectID,
		arg.WorkspaceID,
		arg.ServerID,
		arg.ContainerPort,
		arg.SourceAccess,
		arg.CloneUrl,
		arg.GitRef,
		arg.PrNumber,
		arg.PrUrl,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.ImageRef,
		&i.ContainerPort,
		&i.HostPort,
		&i.ContainerID,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceKind,
		&i.SourceAccess,
		&i.CloneUrl,
		&i.GitRef,
		&i.CommitSha,
		&i.BuiltImageRef,
		&i.RouteUrl,
		&i.ServiceID,
		&i.RolledBackFrom,
		&i.Kind,
		&i.RouteKey,
		&i.PrNumber,
		&i.PrUrl,
	)
	return i, err
}

const createTeardownJob = `-- name: CreateTeardownJob :one

INSERT INTO teardown_jobs (deployment_id, service_id, route_key, environment_id, project_id, workspace_id, server_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, deployment_id, service_id, route_key, environment_id, project_id, workspace_id, server_id, status, message, error, created_at, updated_at
`

type CreateTeardownJobParams struct {
	DeploymentID  string
	ServiceID     string
	RouteKey      string
	EnvironmentID string
	ProjectID     string
	WorkspaceID   string
	ServerID      string
}

// --- teardown_jobs ---
// CreateTeardownJob records a queued teardown of a preview deployment. route_key is the preview's
// container-replacement / Caddy route key (the agent matches plorigo.service={route_key}); the rest
// are denormalized from the preview's deployment row so the claim is self-contained.
func (q *Queries) CreateTeardownJob(ctx context.Context, arg CreateTeardownJobParams) (TeardownJob, error) {
	row := q.db.QueryRow(ctx, createTeardownJob,
		arg.DeploymentID,
		arg.ServiceID,
		arg.RouteKey,
		arg.EnvironmentID,
		arg.ProjectID,
		arg.WorkspaceID,
		arg.ServerID,
	)
	var i TeardownJob
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.ServiceID,
		&i.RouteKey,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.Status,
		&i.Message,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentServerByCredential = `-- name: GetAgentServerByCredential :one
SELECT id, server_id FROM agents WHERE credential_hash = $1
`

type GetAgentServerByCredentialRow struct {
	ID       string
	ServerID string
}

// GetAgentServerByCredential resolves the agent and its server from a durable agent
// credential hash, so the agent-facing Poll/Report RPCs authenticate the caller and
// scope work to its own server (reading the agents table here is the cross-table read
// modules.md Rule 2 permits from a module's postgres.go).
func (q *Queries) GetAgentServerByCredential(ctx context.Context, credentialHash []byte) (GetAgentServerByCredentialRow, error) {
	row := q.db.QueryRow(ctx, getAgentServerByCredential, credentialHash)
	var i GetAgentServerByCredentialRow
	err := row.Scan(&i.ID, &i.ServerID)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at, source_kind, source_access, clone_url, git_ref, commit_sha, built_image_ref, route_url, service_id, rolled_back_from, kind, route_key, pr_number, pr_url FROM deployments WHERE id = $1
`

func (q *Queries) GetDeployment(ctx context.Context, id string) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.ImageRef,
		&i.ContainerPort,
		&i.HostPort,
		&i.ContainerID,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceKind,
		&i.SourceAccess,
		&i.CloneUrl,
		&i.GitRef,
		&i.CommitSha,
		&i.BuiltImageRef,
		&i.RouteUrl,
		&i.ServiceID,
		&i.RolledBackFrom,
		&i.Kind,
		&i.RouteKey,
		&i.PrNumber,
		&i.PrUrl,
	)
	return i, err
}

const getEnvironmentWorkspaceAndProject = `-- name: GetEnvironmentWorkspaceAndProject :one
SELECT p.workspace_id, p.id AS project_id
FROM environments e
JOIN projects p ON p.id = e.project_id
WHERE e.id = $1
`

type GetEnvironmentWorkspaceAndProjectRow struct {
	WorkspaceID string
	ProjectID   string
}

// GetEnvironmentWorkspaceAndProject resolves a deployment target's owning workspace
// and project through the environment's parent project, so this module authorizes and
// denormalizes both onto the deployment without importing environments/projects.
func (q *Queries) GetEnvironmentWorkspaceAndProject(ctx context.Context, id string) (GetEnvironmentWorkspaceAndProjectRow, error) {
	row := q.db.QueryRow(ctx, getEnvironmentWorkspaceAndProject, id)
	var i GetEnvironmentWorkspaceAndProjectRow
	err := row.Scan(&i.WorkspaceID, &i.ProjectID)
	return i, err
}

const getLatestActivePreviewByRouteKey = `-- name: GetLatestActivePreviewByRouteKey :one
SELECT id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at, source_kind, source_access, clone_url, git_ref, commit_sha, built_image_ref, route_url, service_id, rolled_back_from, kind, route_key, pr_number, pr_url FROM deployments
WHERE service_id = $1 AND route_key = $2 AND kind = 'preview' AND status <> 'torndown'
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestActivePreviewByRouteKeyParams struct {
	ServiceID string
	RouteKey  string
}

// GetLatestActivePreviewByRouteKey returns the most recent NOT-yet-torndown preview deployment for
// a route_key, so a webhook PR-close can enqueue a teardown against it. ErrNoRows when there is no
// active preview (already torn down, or never created) — the caller treats that as an idempotent
// no-op.
func (q *Queries) GetLatestActivePreviewByRouteKey(ctx context.Context, arg GetLatestActivePreviewByRouteKeyParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, getLatestActivePreviewByRouteKey, arg.ServiceID, arg.RouteKey)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.ImageRef,
		&i.ContainerPort,
		&i.HostPort,
		&i.ContainerID,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceKind,
		&i.SourceAccess,
		&i.CloneUrl,
		&i.GitRef,
		&i.CommitSha,
		&i.BuiltImageRef,
		&i.RouteUrl,
		&i.ServiceID,
		&i.RolledBackFrom,
		&i.Kind,
		&i.RouteKey,
		&i.PrNumber,
		&i.PrUrl,
	)
	return i, err
}

const getLatestServerForService = `-- name: GetLatestServerForService :one
SELECT server_id FROM deployments
WHERE service_id = $1
ORDER BY created_at DESC
LIMIT 1
`

// GetLatestServerForService returns the server of the service's most recent deployment (any
// status), so a webhook-driven PR preview deploys onto the same server production uses. ErrNoRows
// when the service has never deployed.
func (q *Queries) GetLatestServerForService(ctx context.Context, serviceID string) (string, error) {
	row := q.db.QueryRow(ctx, getLatestServerForService, serviceID)
	var server_id string
	err := row.Scan(&server_id)
	return server_id, err
}

const getTeardownJob = `-- name: GetTeardownJob :one
SELECT id, deployment_id, service_id, route_key, environment_id, project_id, workspace_id, server_id, status, message, error, created_at, updated_at FROM teardown_jobs WHERE id = $1
`

func (q *Queries) GetTeardownJob(ctx context.Context, id string) (TeardownJob, error) {
	row := q.db.QueryRow(ctx, getTeardownJob, id)
	var i TeardownJob
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.ServiceID,
		&i.RouteKey,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.Status,
		&i.Message,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeploymentEvents = `-- name: ListDeploymentEvents :many
SELECT id, deployment_id, seq, kind, status, message, created_at, stream FROM deployment_events
WHERE deployment_id = $1 AND seq > $2
ORDER BY seq
`

type ListDeploymentEventsParams struct {
	DeploymentID string
	Seq          int64
}

func (q *Queries) ListDeploymentEvents(ctx context.Context, arg ListDeploymentEventsParams) ([]DeploymentEvent, error) {
	rows, err := q.db.Query(ctx, listDeploymentEvents, arg.DeploymentID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentEvent{}
	for rows.Next() {
		var i DeploymentEvent
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Seq,
			&i.Kind,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
			&i.Stream,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByEnvironment = `-- name: ListDeploymentsByEnvironment :many
SELECT id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at, source_kind, source_access, clone_url, git_ref, commit_sha, built_image_ref, route_url, service_id, rolled_back_from, kind, route_key, pr_number, pr_url FROM deployments WHERE environment_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentsByEnvironment(ctx context.Context, environmentID string) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.ServerID,
			&i.ImageRef,
			&i.ContainerPort,
			&i.HostPort,
			&i.ContainerID,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceKind,
			&i.SourceAccess,
			&i.CloneUrl,
			&i.GitRef,
			&i.CommitSha,
			&i.BuiltImageRef,
			&i.RouteUrl,
			&i.ServiceID,
			&i.RolledBackFrom,
			&i.Kind,
			&i.RouteKey,
			&i.PrNumber,
			&i.PrUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByProject = `-- name: ListDeploymentsByProject :many
SELECT id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at, source_kind, source_access, clone_url, git_ref, commit_sha, built_image_ref, route_url, service_id, rolled_back_from, kind, route_key, pr_number, pr_url FROM deployments WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentsByProject(ctx context.Context, projectID string) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.ServerID,
			&i.ImageRef,
			&i.ContainerPort,
			&i.HostPort,
			&i.ContainerID,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceKind,
			&i.SourceAccess,
			&i.CloneUrl,
			&i.GitRef,
			&i.CommitSha,
			&i.BuiltImageRef,
			&i.RouteUrl,
			&i.ServiceID,
			&i.RolledBackFrom,
			&i.Kind,
			&i.RouteKey,
			&i.PrNumber,
			&i.PrUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByService = `-- name: ListDeploymentsByService :many
SELECT id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at, source_kind, source_access, clone_url, git_ref, commit_sha, built_image_ref, route_url, service_id, rolled_back_from, kind, route_key, pr_number, pr_url FROM deployments WHERE service_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentsByService(ctx context.Context, serviceID string) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.ServerID,
			&i.ImageRef,
			&i.ContainerPort,
			&i.HostPort,
			&i.ContainerID,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceKind,
			&i.SourceAccess,
			&i.CloneUrl,
			&i.GitRef,
			&i.CommitSha,
			&i.BuiltImageRef,
			&i.RouteUrl,
			&i.ServiceID,
			&i.RolledBackFrom,
			&i.Kind,
			&i.RouteKey,
			&i.PrNumber,
			&i.PrUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByWorkspace = `-- name: ListDeploymentsByWorkspace :many
SELECT id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at, source_kind, source_access, clone_url, git_ref, commit_sha, built_image_ref, route_url, service_id, rolled_back_from, kind, route_key, pr_number, pr_url FROM deployments WHERE workspace_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentsByWorkspace(ctx context.Context, workspaceID string) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.ServerID,
			&i.ImageRef,
			&i.ContainerPort,
			&i.HostPort,
			&i.ContainerID,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceKind,
			&i.SourceAccess,
			&i.CloneUrl,
			&i.GitRef,
			&i.CommitSha,
			&i.BuiltImageRef,
			&i.RouteUrl,
			&i.ServiceID,
			&i.RolledBackFrom,
			&i.Kind,
			&i.RouteKey,
			&i.PrNumber,
			&i.PrUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeardownJobsByService = `-- name: ListTeardownJobsByService :many
SELECT id, deployment_id, service_id, route_key, environment_id, project_id, workspace_id, server_id, status, message, error, created_at, updated_at FROM teardown_jobs WHERE service_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTeardownJobsByService(ctx context.Context, serviceID string) ([]TeardownJob, error) {
	rows, err := q.db.Query(ctx, listTeardownJobsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeardownJob{}
	for rows.Next() {
		var i TeardownJob
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.ServiceID,
			&i.RouteKey,
			&i.EnvironmentID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.ServerID,
			&i.Status,
			&i.Message,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPreviewTornDown = `-- name: MarkPreviewTornDown :exec
UPDATE deployments
SET status = 'torndown', updated_at = now()
WHERE route_key = $1 AND server_id = $2 AND status NOT IN ('failed', 'superseded', 'torndown')
`

type MarkPreviewTornDownParams struct {
	RouteKey string
	ServerID string
}

// MarkPreviewTornDown moves a torn-down preview's still-active deployment rows (same route_key on
// the server) to the terminal 'torndown' status, so the dashboard stops showing the preview as
// running once its container and route are gone. Failed/superseded/already-torndown rows are left
// as they are.
func (q *Queries) MarkPreviewTornDown(ctx context.Context, arg MarkPreviewTornDownParams) error {
	_, err := q.db.Exec(ctx, markPreviewTornDown, arg.RouteKey, arg.ServerID)
	return err
}

const supersedePreviousRunning = `-- name: SupersedePreviousRunning :exec
UPDATE deployments
SET status = 'superseded', updated_at = now()
WHERE route_key = $1 AND server_id = $2 AND status = 'running' AND id <> $3
`

type SupersedePreviousRunningParams struct {
	RouteKey string
	ServerID string
	ID       string
}

// SupersedePreviousRunning marks the prior running deployment with the same route_key on this
// server as superseded once a newer one reaches 'running', so "current" is unambiguous. Keyed
// by route_key (= the service id for a production deployment, a distinct key per preview) so a
// preview never supersedes production (or another preview), and a sibling service in the same
// environment is never superseded.
func (q *Queries) SupersedePreviousRunning(ctx context.Context, arg SupersedePreviousRunningParams) error {
	_, err := q.db.Exec(ctx, supersedePreviousRunning, arg.RouteKey, arg.ServerID, arg.ID)
	return err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :one
UPDATE deployments
SET status = $1,
    message = CASE WHEN $2::text <> '' THEN $2::text ELSE message END,
    host_port = CASE WHEN $3::integer > 0 THEN $3::integer ELSE host_port END,
    container_id = CASE WHEN $4::text <> '' THEN $4::text ELSE container_id END,
    commit_sha = CASE WHEN $5::text <> '' THEN $5::text ELSE commit_sha END,
    built_image_ref = CASE WHEN $6::text <> '' THEN $6::text ELSE built_image_ref END,
    route_url = CASE WHEN $7::text <> '' THEN $7::text ELSE route_url END,
    updated_at = now()
WHERE id = $8
RETURNING id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at, source_kind, source_access, clone_url, git_ref, commit_sha, built_image_ref, route_url, service_id, rolled_back_from, kind, route_key, pr_number, pr_url
`

type UpdateDeploymentStatusParams struct {
	Status        string
	Message       string
	HostPort      int32
	ContainerID   string
	CommitSha     string
	BuiltImageRef string
	RouteUrl      string
	ID            string
}

// UpdateDeploymentStatus records a status transition. host_port, container_id, commit_sha,
// built_image_ref, route_url, and message are only known at certain points in the flow,
// so a zero/empty value never clobbers a set one. (The runtime-log tail loop re-reports
// status='running' with an empty message to attach new log lines; a blank message must
// not wipe the deployment's status line.)
func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, updateDeploymentStatus,
		arg.Status,
		arg.Message,
		arg.HostPort,
		arg.ContainerID,
		arg.CommitSha,
		arg.BuiltImageRef,
		arg.RouteUrl,
		arg.ID,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.ImageRef,
		&i.ContainerPort,
		&i.HostPort,
		&i.ContainerID,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceKind,
		&i.SourceAccess,
		&i.CloneUrl,
		&i.GitRef,
		&i.CommitSha,
		&i.BuiltImageRef,
		&i.RouteUrl,
		&i.ServiceID,
		&i.RolledBackFrom,
		&i.Kind,
		&i.RouteKey,
		&i.PrNumber,
		&i.PrUrl,
	)
	return i, err
}

const updateTeardownStatus = `-- name: UpdateTeardownStatus :one
UPDATE teardown_jobs
SET status = $1,
    message = CASE WHEN $2::text <> '' THEN $2::text ELSE message END,
    error = CASE WHEN $3::text <> '' THEN $3::text ELSE error END,
    updated_at = now()
WHERE id = $4
RETURNING id, deployment_id, service_id, route_key, environment_id, project_id, workspace_id, server_id, status, message, error, created_at, updated_at
`

type UpdateTeardownStatusParams struct {
	Status  string
	Message string
	Error   string
	ID      string
}

// UpdateTeardownStatus records a status transition; a zero/empty message or error never clobbers a
// value already set.
func (q *Queries) UpdateTeardownStatus(ctx context.Context, arg UpdateTeardownStatusParams) (TeardownJob, error) {
	row := q.db.QueryRow(ctx, updateTeardownStatus,
		arg.Status,
		arg.Message,
		arg.Error,
		arg.ID,
	)
	var i TeardownJob
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.ServiceID,
		&i.RouteKey,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.Status,
		&i.Message,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
