// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package db

import (
	"context"
)

const appendDeploymentEvent = `-- name: AppendDeploymentEvent :one
INSERT INTO deployment_events (deployment_id, kind, status, message, stream)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, deployment_id, seq, kind, status, message, created_at, stream
`

type AppendDeploymentEventParams struct {
	DeploymentID string
	Kind         string
	Status       string
	Message      string
	Stream       string
}

func (q *Queries) AppendDeploymentEvent(ctx context.Context, arg AppendDeploymentEventParams) (DeploymentEvent, error) {
	row := q.db.QueryRow(ctx, appendDeploymentEvent,
		arg.DeploymentID,
		arg.Kind,
		arg.Status,
		arg.Message,
		arg.Stream,
	)
	var i DeploymentEvent
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.Seq,
		&i.Kind,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.Stream,
	)
	return i, err
}

const claimNextDeploymentForServer = `-- name: ClaimNextDeploymentForServer :one
UPDATE deployments
SET status = 'assigned', updated_at = now()
WHERE id = (
    SELECT d.id FROM deployments d
    WHERE d.server_id = $1 AND d.status = 'queued'
    ORDER BY d.created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at, source_kind, source_access, clone_url, git_ref, commit_sha, built_image_ref, route_url, service_id, rolled_back_from
`

// ClaimNextDeploymentForServer atomically claims the oldest queued deployment for a
// server, flipping it to 'assigned' so concurrent polls (or a restart mid-deploy)
// never grab the same one. FOR UPDATE SKIP LOCKED + the single statement is the
// single-statement-claim pattern (cf. ConsumeAgentRegistrationToken in agents.sql).
func (q *Queries) ClaimNextDeploymentForServer(ctx context.Context, serverID string) (Deployment, error) {
	row := q.db.QueryRow(ctx, claimNextDeploymentForServer, serverID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.ImageRef,
		&i.ContainerPort,
		&i.HostPort,
		&i.ContainerID,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceKind,
		&i.SourceAccess,
		&i.CloneUrl,
		&i.GitRef,
		&i.CommitSha,
		&i.BuiltImageRef,
		&i.RouteUrl,
		&i.ServiceID,
		&i.RolledBackFrom,
	)
	return i, err
}

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (service_id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, rolled_back_from)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at, source_kind, source_access, clone_url, git_ref, commit_sha, built_image_ref, route_url, service_id, rolled_back_from
`

type CreateDeploymentParams struct {
	ServiceID      string
	EnvironmentID  string
	ProjectID      string
	WorkspaceID    string
	ServerID       string
	ImageRef       string
	ContainerPort  int32
	RolledBackFrom *string
}

// rolled_back_from is NULL for a normal deploy and set to the restored deployment's id when
// this row is a rollback (see RollbackDeployment).
func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.ServiceID,
		arg.EnvironmentID,
		arg.ProjectID,
		arg.WorkspaceID,
		arg.ServerID,
		arg.ImageRef,
		arg.ContainerPort,
		arg.RolledBackFrom,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.ImageRef,
		&i.ContainerPort,
		&i.HostPort,
		&i.ContainerID,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceKind,
		&i.SourceAccess,
		&i.CloneUrl,
		&i.GitRef,
		&i.CommitSha,
		&i.BuiltImageRef,
		&i.RouteUrl,
		&i.ServiceID,
		&i.RolledBackFrom,
	)
	return i, err
}

const createDeploymentFromGit = `-- name: CreateDeploymentFromGit :one
INSERT INTO deployments (
    service_id, environment_id, project_id, workspace_id, server_id,
    container_port, source_kind, source_access, clone_url, git_ref, rolled_back_from
)
VALUES ($1, $2, $3, $4, $5, $6, 'git', $7, $8, $9, $10)
RETURNING id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at, source_kind, source_access, clone_url, git_ref, commit_sha, built_image_ref, route_url, service_id, rolled_back_from
`

type CreateDeploymentFromGitParams struct {
	ServiceID      string
	EnvironmentID  string
	ProjectID      string
	WorkspaceID    string
	ServerID       string
	ContainerPort  int32
	SourceAccess   string
	CloneUrl       string
	GitRef         string
	RolledBackFrom *string
}

// CreateDeploymentFromGit records a queued deployment whose source is a repo+ref to clone
// and build on the server (image_ref is filled in by the agent after the build). See
// docs/architecture/deployment-engine.md.
func (q *Queries) CreateDeploymentFromGit(ctx context.Context, arg CreateDeploymentFromGitParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeploymentFromGit,
		arg.ServiceID,
		arg.EnvironmentID,
		arg.ProjectID,
		arg.WorkspaceID,
		arg.ServerID,
		arg.ContainerPort,
		arg.SourceAccess,
		arg.CloneUrl,
		arg.GitRef,
		arg.RolledBackFrom,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.ImageRef,
		&i.ContainerPort,
		&i.HostPort,
		&i.ContainerID,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceKind,
		&i.SourceAccess,
		&i.CloneUrl,
		&i.GitRef,
		&i.CommitSha,
		&i.BuiltImageRef,
		&i.RouteUrl,
		&i.ServiceID,
		&i.RolledBackFrom,
	)
	return i, err
}

const getAgentServerByCredential = `-- name: GetAgentServerByCredential :one
SELECT id, server_id FROM agents WHERE credential_hash = $1
`

type GetAgentServerByCredentialRow struct {
	ID       string
	ServerID string
}

// GetAgentServerByCredential resolves the agent and its server from a durable agent
// credential hash, so the agent-facing Poll/Report RPCs authenticate the caller and
// scope work to its own server (reading the agents table here is the cross-table read
// modules.md Rule 2 permits from a module's postgres.go).
func (q *Queries) GetAgentServerByCredential(ctx context.Context, credentialHash []byte) (GetAgentServerByCredentialRow, error) {
	row := q.db.QueryRow(ctx, getAgentServerByCredential, credentialHash)
	var i GetAgentServerByCredentialRow
	err := row.Scan(&i.ID, &i.ServerID)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at, source_kind, source_access, clone_url, git_ref, commit_sha, built_image_ref, route_url, service_id, rolled_back_from FROM deployments WHERE id = $1
`

func (q *Queries) GetDeployment(ctx context.Context, id string) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.ImageRef,
		&i.ContainerPort,
		&i.HostPort,
		&i.ContainerID,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceKind,
		&i.SourceAccess,
		&i.CloneUrl,
		&i.GitRef,
		&i.CommitSha,
		&i.BuiltImageRef,
		&i.RouteUrl,
		&i.ServiceID,
		&i.RolledBackFrom,
	)
	return i, err
}

const getEnvironmentWorkspaceAndProject = `-- name: GetEnvironmentWorkspaceAndProject :one
SELECT p.workspace_id, p.id AS project_id
FROM environments e
JOIN projects p ON p.id = e.project_id
WHERE e.id = $1
`

type GetEnvironmentWorkspaceAndProjectRow struct {
	WorkspaceID string
	ProjectID   string
}

// GetEnvironmentWorkspaceAndProject resolves a deployment target's owning workspace
// and project through the environment's parent project, so this module authorizes and
// denormalizes both onto the deployment without importing environments/projects.
func (q *Queries) GetEnvironmentWorkspaceAndProject(ctx context.Context, id string) (GetEnvironmentWorkspaceAndProjectRow, error) {
	row := q.db.QueryRow(ctx, getEnvironmentWorkspaceAndProject, id)
	var i GetEnvironmentWorkspaceAndProjectRow
	err := row.Scan(&i.WorkspaceID, &i.ProjectID)
	return i, err
}

const listDeploymentEvents = `-- name: ListDeploymentEvents :many
SELECT id, deployment_id, seq, kind, status, message, created_at, stream FROM deployment_events
WHERE deployment_id = $1 AND seq > $2
ORDER BY seq
`

type ListDeploymentEventsParams struct {
	DeploymentID string
	Seq          int64
}

func (q *Queries) ListDeploymentEvents(ctx context.Context, arg ListDeploymentEventsParams) ([]DeploymentEvent, error) {
	rows, err := q.db.Query(ctx, listDeploymentEvents, arg.DeploymentID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentEvent{}
	for rows.Next() {
		var i DeploymentEvent
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Seq,
			&i.Kind,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
			&i.Stream,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByEnvironment = `-- name: ListDeploymentsByEnvironment :many
SELECT id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at, source_kind, source_access, clone_url, git_ref, commit_sha, built_image_ref, route_url, service_id, rolled_back_from FROM deployments WHERE environment_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentsByEnvironment(ctx context.Context, environmentID string) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.ServerID,
			&i.ImageRef,
			&i.ContainerPort,
			&i.HostPort,
			&i.ContainerID,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceKind,
			&i.SourceAccess,
			&i.CloneUrl,
			&i.GitRef,
			&i.CommitSha,
			&i.BuiltImageRef,
			&i.RouteUrl,
			&i.ServiceID,
			&i.RolledBackFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByProject = `-- name: ListDeploymentsByProject :many
SELECT id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at, source_kind, source_access, clone_url, git_ref, commit_sha, built_image_ref, route_url, service_id, rolled_back_from FROM deployments WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentsByProject(ctx context.Context, projectID string) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.ServerID,
			&i.ImageRef,
			&i.ContainerPort,
			&i.HostPort,
			&i.ContainerID,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceKind,
			&i.SourceAccess,
			&i.CloneUrl,
			&i.GitRef,
			&i.CommitSha,
			&i.BuiltImageRef,
			&i.RouteUrl,
			&i.ServiceID,
			&i.RolledBackFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByService = `-- name: ListDeploymentsByService :many
SELECT id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at, source_kind, source_access, clone_url, git_ref, commit_sha, built_image_ref, route_url, service_id, rolled_back_from FROM deployments WHERE service_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentsByService(ctx context.Context, serviceID string) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.ServerID,
			&i.ImageRef,
			&i.ContainerPort,
			&i.HostPort,
			&i.ContainerID,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceKind,
			&i.SourceAccess,
			&i.CloneUrl,
			&i.GitRef,
			&i.CommitSha,
			&i.BuiltImageRef,
			&i.RouteUrl,
			&i.ServiceID,
			&i.RolledBackFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByWorkspace = `-- name: ListDeploymentsByWorkspace :many
SELECT id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at, source_kind, source_access, clone_url, git_ref, commit_sha, built_image_ref, route_url, service_id, rolled_back_from FROM deployments WHERE workspace_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentsByWorkspace(ctx context.Context, workspaceID string) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.ServerID,
			&i.ImageRef,
			&i.ContainerPort,
			&i.HostPort,
			&i.ContainerID,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceKind,
			&i.SourceAccess,
			&i.CloneUrl,
			&i.GitRef,
			&i.CommitSha,
			&i.BuiltImageRef,
			&i.RouteUrl,
			&i.ServiceID,
			&i.RolledBackFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedePreviousRunning = `-- name: SupersedePreviousRunning :exec
UPDATE deployments
SET status = 'superseded', updated_at = now()
WHERE service_id = $1 AND server_id = $2 AND status = 'running' AND id <> $3
`

type SupersedePreviousRunningParams struct {
	ServiceID string
	ServerID  string
	ID        string
}

// SupersedePreviousRunning marks the SERVICE's prior running deployment on this server as
// superseded once a newer one reaches 'running', so "current" is unambiguous. Keyed by
// service (not environment) so deploying one service never supersedes a sibling service
// running in the same environment.
func (q *Queries) SupersedePreviousRunning(ctx context.Context, arg SupersedePreviousRunningParams) error {
	_, err := q.db.Exec(ctx, supersedePreviousRunning, arg.ServiceID, arg.ServerID, arg.ID)
	return err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :one
UPDATE deployments
SET status = $1,
    message = CASE WHEN $2::text <> '' THEN $2::text ELSE message END,
    host_port = CASE WHEN $3::integer > 0 THEN $3::integer ELSE host_port END,
    container_id = CASE WHEN $4::text <> '' THEN $4::text ELSE container_id END,
    commit_sha = CASE WHEN $5::text <> '' THEN $5::text ELSE commit_sha END,
    built_image_ref = CASE WHEN $6::text <> '' THEN $6::text ELSE built_image_ref END,
    route_url = CASE WHEN $7::text <> '' THEN $7::text ELSE route_url END,
    updated_at = now()
WHERE id = $8
RETURNING id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at, source_kind, source_access, clone_url, git_ref, commit_sha, built_image_ref, route_url, service_id, rolled_back_from
`

type UpdateDeploymentStatusParams struct {
	Status        string
	Message       string
	HostPort      int32
	ContainerID   string
	CommitSha     string
	BuiltImageRef string
	RouteUrl      string
	ID            string
}

// UpdateDeploymentStatus records a status transition. host_port, container_id, commit_sha,
// built_image_ref, route_url, and message are only known at certain points in the flow,
// so a zero/empty value never clobbers a set one. (The runtime-log tail loop re-reports
// status='running' with an empty message to attach new log lines; a blank message must
// not wipe the deployment's status line.)
func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, updateDeploymentStatus,
		arg.Status,
		arg.Message,
		arg.HostPort,
		arg.ContainerID,
		arg.CommitSha,
		arg.BuiltImageRef,
		arg.RouteUrl,
		arg.ID,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.ImageRef,
		&i.ContainerPort,
		&i.HostPort,
		&i.ContainerID,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceKind,
		&i.SourceAccess,
		&i.CloneUrl,
		&i.GitRef,
		&i.CommitSha,
		&i.BuiltImageRef,
		&i.RouteUrl,
		&i.ServiceID,
		&i.RolledBackFrom,
	)
	return i, err
}
