// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package db

import (
	"context"
)

const appendDeploymentEvent = `-- name: AppendDeploymentEvent :one
INSERT INTO deployment_events (deployment_id, kind, status, message)
VALUES ($1, $2, $3, $4)
RETURNING id, deployment_id, seq, kind, status, message, created_at
`

type AppendDeploymentEventParams struct {
	DeploymentID string
	Kind         string
	Status       string
	Message      string
}

func (q *Queries) AppendDeploymentEvent(ctx context.Context, arg AppendDeploymentEventParams) (DeploymentEvent, error) {
	row := q.db.QueryRow(ctx, appendDeploymentEvent,
		arg.DeploymentID,
		arg.Kind,
		arg.Status,
		arg.Message,
	)
	var i DeploymentEvent
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.Seq,
		&i.Kind,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const claimNextDeploymentForServer = `-- name: ClaimNextDeploymentForServer :one
UPDATE deployments
SET status = 'assigned', updated_at = now()
WHERE id = (
    SELECT d.id FROM deployments d
    WHERE d.server_id = $1 AND d.status = 'queued'
    ORDER BY d.created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at
`

// ClaimNextDeploymentForServer atomically claims the oldest queued deployment for a
// server, flipping it to 'assigned' so concurrent polls (or a restart mid-deploy)
// never grab the same one. FOR UPDATE SKIP LOCKED + the single statement is the
// single-statement-claim pattern (cf. ConsumeAgentRegistrationToken in agents.sql).
func (q *Queries) ClaimNextDeploymentForServer(ctx context.Context, serverID string) (Deployment, error) {
	row := q.db.QueryRow(ctx, claimNextDeploymentForServer, serverID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.ImageRef,
		&i.ContainerPort,
		&i.HostPort,
		&i.ContainerID,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (environment_id, project_id, workspace_id, server_id, image_ref, container_port)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at
`

type CreateDeploymentParams struct {
	EnvironmentID string
	ProjectID     string
	WorkspaceID   string
	ServerID      string
	ImageRef      string
	ContainerPort int32
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.EnvironmentID,
		arg.ProjectID,
		arg.WorkspaceID,
		arg.ServerID,
		arg.ImageRef,
		arg.ContainerPort,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.ImageRef,
		&i.ContainerPort,
		&i.HostPort,
		&i.ContainerID,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentServerByCredential = `-- name: GetAgentServerByCredential :one
SELECT id, server_id FROM agents WHERE credential_hash = $1
`

type GetAgentServerByCredentialRow struct {
	ID       string
	ServerID string
}

// GetAgentServerByCredential resolves the agent and its server from a durable agent
// credential hash, so the agent-facing Poll/Report RPCs authenticate the caller and
// scope work to its own server (reading the agents table here is the cross-table read
// modules.md Rule 2 permits from a module's postgres.go).
func (q *Queries) GetAgentServerByCredential(ctx context.Context, credentialHash []byte) (GetAgentServerByCredentialRow, error) {
	row := q.db.QueryRow(ctx, getAgentServerByCredential, credentialHash)
	var i GetAgentServerByCredentialRow
	err := row.Scan(&i.ID, &i.ServerID)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at FROM deployments WHERE id = $1
`

func (q *Queries) GetDeployment(ctx context.Context, id string) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.ImageRef,
		&i.ContainerPort,
		&i.HostPort,
		&i.ContainerID,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvironmentWorkspaceAndProject = `-- name: GetEnvironmentWorkspaceAndProject :one
SELECT p.workspace_id, p.id AS project_id
FROM environments e
JOIN projects p ON p.id = e.project_id
WHERE e.id = $1
`

type GetEnvironmentWorkspaceAndProjectRow struct {
	WorkspaceID string
	ProjectID   string
}

// GetEnvironmentWorkspaceAndProject resolves a deployment target's owning workspace
// and project through the environment's parent project, so this module authorizes and
// denormalizes both onto the deployment without importing environments/projects.
func (q *Queries) GetEnvironmentWorkspaceAndProject(ctx context.Context, id string) (GetEnvironmentWorkspaceAndProjectRow, error) {
	row := q.db.QueryRow(ctx, getEnvironmentWorkspaceAndProject, id)
	var i GetEnvironmentWorkspaceAndProjectRow
	err := row.Scan(&i.WorkspaceID, &i.ProjectID)
	return i, err
}

const listDeploymentEvents = `-- name: ListDeploymentEvents :many
SELECT id, deployment_id, seq, kind, status, message, created_at FROM deployment_events
WHERE deployment_id = $1 AND seq > $2
ORDER BY seq
`

type ListDeploymentEventsParams struct {
	DeploymentID string
	Seq          int64
}

func (q *Queries) ListDeploymentEvents(ctx context.Context, arg ListDeploymentEventsParams) ([]DeploymentEvent, error) {
	rows, err := q.db.Query(ctx, listDeploymentEvents, arg.DeploymentID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentEvent{}
	for rows.Next() {
		var i DeploymentEvent
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Seq,
			&i.Kind,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByEnvironment = `-- name: ListDeploymentsByEnvironment :many
SELECT id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at FROM deployments WHERE environment_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentsByEnvironment(ctx context.Context, environmentID string) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.ServerID,
			&i.ImageRef,
			&i.ContainerPort,
			&i.HostPort,
			&i.ContainerID,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByProject = `-- name: ListDeploymentsByProject :many
SELECT id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at FROM deployments WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentsByProject(ctx context.Context, projectID string) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.ServerID,
			&i.ImageRef,
			&i.ContainerPort,
			&i.HostPort,
			&i.ContainerID,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByWorkspace = `-- name: ListDeploymentsByWorkspace :many
SELECT id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at FROM deployments WHERE workspace_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentsByWorkspace(ctx context.Context, workspaceID string) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.ServerID,
			&i.ImageRef,
			&i.ContainerPort,
			&i.HostPort,
			&i.ContainerID,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedePreviousRunning = `-- name: SupersedePreviousRunning :exec
UPDATE deployments
SET status = 'superseded', updated_at = now()
WHERE environment_id = $1 AND server_id = $2 AND status = 'running' AND id <> $3
`

type SupersedePreviousRunningParams struct {
	EnvironmentID string
	ServerID      string
	ID            string
}

// SupersedePreviousRunning marks the environment's prior running deployment on this
// server as superseded once a newer one reaches 'running', so "current" is unambiguous.
func (q *Queries) SupersedePreviousRunning(ctx context.Context, arg SupersedePreviousRunningParams) error {
	_, err := q.db.Exec(ctx, supersedePreviousRunning, arg.EnvironmentID, arg.ServerID, arg.ID)
	return err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :one
UPDATE deployments
SET status = $1,
    message = $2,
    host_port = CASE WHEN $3::integer > 0 THEN $3::integer ELSE host_port END,
    container_id = CASE WHEN $4::text <> '' THEN $4::text ELSE container_id END,
    updated_at = now()
WHERE id = $5
RETURNING id, environment_id, project_id, workspace_id, server_id, image_ref, container_port, host_port, container_id, status, message, created_at, updated_at
`

type UpdateDeploymentStatusParams struct {
	Status      string
	Message     string
	HostPort    int32
	ContainerID string
	ID          string
}

// UpdateDeploymentStatus records a status transition. host_port and container_id are
// only known later in the flow, so a zero/empty value never clobbers a set one.
func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, updateDeploymentStatus,
		arg.Status,
		arg.Message,
		arg.HostPort,
		arg.ContainerID,
		arg.ID,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.ServerID,
		&i.ImageRef,
		&i.ContainerPort,
		&i.HostPort,
		&i.ContainerID,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
