// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domains.sql

package db

import (
	"context"
)

const createDomain = `-- name: CreateDomain :one

INSERT INTO domains (
    service_id, environment_id, project_id, workspace_id, hostname, status, status_message
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, service_id, environment_id, project_id, workspace_id, hostname, status, status_message, last_checked_at, created_at, updated_at
`

type CreateDomainParams struct {
	ServiceID     string
	EnvironmentID string
	ProjectID     string
	WorkspaceID   string
	Hostname      string
	Status        string
	StatusMessage string
}

// Custom domains are hostnames attached to a service. A service can have many domains,
// but a hostname is unique within a workspace so traffic can never ambiguously route to
// two services.
func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, createDomain,
		arg.ServiceID,
		arg.EnvironmentID,
		arg.ProjectID,
		arg.WorkspaceID,
		arg.Hostname,
		arg.Status,
		arg.StatusMessage,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.Hostname,
		&i.Status,
		&i.StatusMessage,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDomain = `-- name: DeleteDomain :one
DELETE FROM domains WHERE id = $1 RETURNING id
`

func (q *Queries) DeleteDomain(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, deleteDomain, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const getDomain = `-- name: GetDomain :one
SELECT id, service_id, environment_id, project_id, workspace_id, hostname, status, status_message, last_checked_at, created_at, updated_at FROM domains WHERE id = $1
`

func (q *Queries) GetDomain(ctx context.Context, id string) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomain, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.Hostname,
		&i.Status,
		&i.StatusMessage,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomainServiceForCreate = `-- name: GetDomainServiceForCreate :one
SELECT id, environment_id, project_id, workspace_id, visibility, route_url
FROM services
WHERE id = $1
`

type GetDomainServiceForCreateRow struct {
	ID            string
	EnvironmentID string
	ProjectID     string
	WorkspaceID   string
	Visibility    string
	RouteUrl      string
}

// GetDomainServiceForCreate resolves the target service and its routing prerequisites.
// Domains are only useful for public services with a generated route_url, but we still
// persist blocked rows so the dashboard can show the next action.
func (q *Queries) GetDomainServiceForCreate(ctx context.Context, id string) (GetDomainServiceForCreateRow, error) {
	row := q.db.QueryRow(ctx, getDomainServiceForCreate, id)
	var i GetDomainServiceForCreateRow
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.Visibility,
		&i.RouteUrl,
	)
	return i, err
}

const listDomainsByProject = `-- name: ListDomainsByProject :many
SELECT id, service_id, environment_id, project_id, workspace_id, hostname, status, status_message, last_checked_at, created_at, updated_at FROM domains WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDomainsByProject(ctx context.Context, projectID string) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listDomainsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.EnvironmentID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.Hostname,
			&i.Status,
			&i.StatusMessage,
			&i.LastCheckedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainsByService = `-- name: ListDomainsByService :many
SELECT id, service_id, environment_id, project_id, workspace_id, hostname, status, status_message, last_checked_at, created_at, updated_at FROM domains WHERE service_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDomainsByService(ctx context.Context, serviceID string) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listDomainsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.EnvironmentID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.Hostname,
			&i.Status,
			&i.StatusMessage,
			&i.LastCheckedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainsByWorkspace = `-- name: ListDomainsByWorkspace :many
SELECT id, service_id, environment_id, project_id, workspace_id, hostname, status, status_message, last_checked_at, created_at, updated_at FROM domains WHERE workspace_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDomainsByWorkspace(ctx context.Context, workspaceID string) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listDomainsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.EnvironmentID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.Hostname,
			&i.Status,
			&i.StatusMessage,
			&i.LastCheckedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDomainsRouteSync = `-- name: MarkDomainsRouteSync :exec
UPDATE domains
SET status = $3,
    status_message = $4,
    updated_at = now()
WHERE service_id = $1
  AND hostname = ANY($2::text[])
  AND status IN ('verified', 'active', 'failed')
`

type MarkDomainsRouteSyncParams struct {
	ServiceID     string
	Column2       []string
	Status        string
	StatusMessage string
}

func (q *Queries) MarkDomainsRouteSync(ctx context.Context, arg MarkDomainsRouteSyncParams) error {
	_, err := q.db.Exec(ctx, markDomainsRouteSync,
		arg.ServiceID,
		arg.Column2,
		arg.Status,
		arg.StatusMessage,
	)
	return err
}

const updateDomainVerification = `-- name: UpdateDomainVerification :one
UPDATE domains
SET status = $2,
    status_message = $3,
    last_checked_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, service_id, environment_id, project_id, workspace_id, hostname, status, status_message, last_checked_at, created_at, updated_at
`

type UpdateDomainVerificationParams struct {
	ID            string
	Status        string
	StatusMessage string
}

func (q *Queries) UpdateDomainVerification(ctx context.Context, arg UpdateDomainVerificationParams) (Domain, error) {
	row := q.db.QueryRow(ctx, updateDomainVerification, arg.ID, arg.Status, arg.StatusMessage)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.Hostname,
		&i.Status,
		&i.StatusMessage,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifiedDomainsForServices = `-- name: VerifiedDomainsForServices :many
SELECT service_id, hostname
FROM domains
WHERE service_id = ANY($1::uuid[])
  AND status IN ('verified', 'active')
ORDER BY service_id, hostname
`

type VerifiedDomainsForServicesRow struct {
	ServiceID string
	Hostname  string
}

func (q *Queries) VerifiedDomainsForServices(ctx context.Context, dollar_1 []string) ([]VerifiedDomainsForServicesRow, error) {
	rows, err := q.db.Query(ctx, verifiedDomainsForServices, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VerifiedDomainsForServicesRow{}
	for rows.Next() {
		var i VerifiedDomainsForServicesRow
		if err := rows.Scan(&i.ServiceID, &i.Hostname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
