// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environments.sql

package db

import (
	"context"
	"time"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (project_id, name, slug, type)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, name, slug, type, created_at
`

type CreateEnvironmentParams struct {
	ProjectID string
	Name      string
	Slug      string
	Type      string
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment,
		arg.ProjectID,
		arg.Name,
		arg.Slug,
		arg.Type,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT e.id, e.project_id, e.name, e.slug, e.type, e.created_at, p.workspace_id
FROM environments e
JOIN projects p ON p.id = e.project_id
WHERE e.id = $1
`

type GetEnvironmentRow struct {
	ID          string
	ProjectID   string
	Name        string
	Slug        string
	Type        string
	CreatedAt   time.Time
	WorkspaceID string
}

// Joins the parent project so the caller can authorize against the owning
// workspace (environments are project-scoped; authorization is workspace-scoped).
func (q *Queries) GetEnvironment(ctx context.Context, id string) (GetEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, getEnvironment, id)
	var i GetEnvironmentRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.CreatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const getProjectWorkspaceID = `-- name: GetProjectWorkspaceID :one
SELECT workspace_id FROM projects WHERE id = $1
`

// Resolves a project's owning workspace, so a project-scoped action can be
// authorized and audited against the workspace.
func (q *Queries) GetProjectWorkspaceID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getProjectWorkspaceID, id)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const listEnvironmentsByProject = `-- name: ListEnvironmentsByProject :many
SELECT id, project_id, name, slug, type, created_at
FROM environments
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListEnvironmentsByProject(ctx context.Context, projectID string) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Slug,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
