// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: envvars.sql

package db

import (
	"context"
)

const deleteEnvVar = `-- name: DeleteEnvVar :one
DELETE FROM env_vars
WHERE service_id = $1 AND key = $2
RETURNING id
`

type DeleteEnvVarParams struct {
	ServiceID string
	Key       string
}

// RETURNING id lets the caller tell a real delete from a no-op (no row -> ErrNoRows
// -> NotFound), so a delete that removed nothing is never audited as a change.
func (q *Queries) DeleteEnvVar(ctx context.Context, arg DeleteEnvVarParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteEnvVar, arg.ServiceID, arg.Key)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getServiceWorkspaceID = `-- name: GetServiceWorkspaceID :one
SELECT workspace_id FROM services WHERE id = $1
`

// Resolves a service's owning workspace (denormalized onto the service row), so this
// service-scoped module can authorize and audit against the workspace.
func (q *Queries) GetServiceWorkspaceID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getServiceWorkspaceID, id)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const listEnvVarsByService = `-- name: ListEnvVarsByService :many
SELECT id, key, value, created_at, updated_at, service_id FROM env_vars
WHERE service_id = $1
ORDER BY key
`

func (q *Queries) ListEnvVarsByService(ctx context.Context, serviceID string) ([]EnvVar, error) {
	rows, err := q.db.Query(ctx, listEnvVarsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvVar{}
	for rows.Next() {
		var i EnvVar
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEnvVar = `-- name: UpsertEnvVar :one
INSERT INTO env_vars (service_id, key, value)
VALUES ($1, $2, $3)
ON CONFLICT (service_id, key)
DO UPDATE SET value = EXCLUDED.value, updated_at = now()
RETURNING id, key, value, created_at, updated_at, service_id
`

type UpsertEnvVarParams struct {
	ServiceID string
	Key       string
	Value     string
}

// Create-or-update by (service_id, key). The conflict is the success path (env vars are
// mutable config), so callers never see an AlreadyExists error. RETURNING yields the row id
// on both the insert and the update path, for the audit target.
func (q *Queries) UpsertEnvVar(ctx context.Context, arg UpsertEnvVarParams) (EnvVar, error) {
	row := q.db.QueryRow(ctx, upsertEnvVar, arg.ServiceID, arg.Key, arg.Value)
	var i EnvVar
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceID,
	)
	return i, err
}
