// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: envvars.sql

package db

import (
	"context"
)

const deleteEnvVar = `-- name: DeleteEnvVar :one
DELETE FROM env_vars
WHERE environment_id = $1 AND key = $2
RETURNING id
`

type DeleteEnvVarParams struct {
	EnvironmentID string
	Key           string
}

// RETURNING id lets the caller tell a real delete from a no-op (no row -> ErrNoRows
// -> NotFound), so a delete that removed nothing is never audited as a change.
func (q *Queries) DeleteEnvVar(ctx context.Context, arg DeleteEnvVarParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteEnvVar, arg.EnvironmentID, arg.Key)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getEnvironmentWorkspaceID = `-- name: GetEnvironmentWorkspaceID :one
SELECT p.workspace_id
FROM environments e
JOIN projects p ON p.id = e.project_id
WHERE e.id = $1
`

// Resolves an environment's owning workspace through its parent project, so this
// environment-scoped module can authorize and audit against the workspace.
func (q *Queries) GetEnvironmentWorkspaceID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getEnvironmentWorkspaceID, id)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const listEnvVarsByEnvironment = `-- name: ListEnvVarsByEnvironment :many
SELECT id, environment_id, key, value, created_at, updated_at
FROM env_vars
WHERE environment_id = $1
ORDER BY key
`

func (q *Queries) ListEnvVarsByEnvironment(ctx context.Context, environmentID string) ([]EnvVar, error) {
	rows, err := q.db.Query(ctx, listEnvVarsByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvVar{}
	for rows.Next() {
		var i EnvVar
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEnvVar = `-- name: UpsertEnvVar :one
INSERT INTO env_vars (environment_id, key, value)
VALUES ($1, $2, $3)
ON CONFLICT (environment_id, key)
DO UPDATE SET value = EXCLUDED.value, updated_at = now()
RETURNING id, environment_id, key, value, created_at, updated_at
`

type UpsertEnvVarParams struct {
	EnvironmentID string
	Key           string
	Value         string
}

// Create-or-update by (environment_id, key). The conflict is the success path (env
// vars are mutable config), so callers never see an AlreadyExists error. RETURNING
// yields the row id on both the insert and the update path, for the audit target.
func (q *Queries) UpsertEnvVar(ctx context.Context, arg UpsertEnvVarParams) (EnvVar, error) {
	row := q.db.QueryRow(ctx, upsertEnvVar, arg.EnvironmentID, arg.Key, arg.Value)
	var i EnvVar
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
