// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: githubapp.sql

package db

import (
	"context"
	"time"
)

const deleteGitHubAppConfig = `-- name: DeleteGitHubAppConfig :exec
DELETE FROM github_app_config
WHERE singleton = true
`

// Remove the stored App (e.g. before re-registering or to fall back to env config).
func (q *Queries) DeleteGitHubAppConfig(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteGitHubAppConfig)
	return err
}

const getGitHubAppConfig = `-- name: GetGitHubAppConfig :one
SELECT app_id, app_slug, client_id, created_at, updated_at
FROM github_app_config
WHERE singleton = true
`

type GetGitHubAppConfigRow struct {
	AppID     string
	AppSlug   string
	ClientID  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Non-secret metadata for the configured App. Metadata only — never the sealed key/secret.
func (q *Queries) GetGitHubAppConfig(ctx context.Context) (GetGitHubAppConfigRow, error) {
	row := q.db.QueryRow(ctx, getGitHubAppConfig)
	var i GetGitHubAppConfigRow
	err := row.Scan(
		&i.AppID,
		&i.AppSlug,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSealedGitHubAppConfig = `-- name: GetSealedGitHubAppConfig :one
SELECT app_id, app_slug, client_id, sealed_private_key, sealed_webhook_secret, sealed_client_secret
FROM github_app_config
WHERE singleton = true
`

type GetSealedGitHubAppConfigRow struct {
	AppID               string
	AppSlug             string
	ClientID            string
	SealedPrivateKey    []byte
	SealedWebhookSecret []byte
	SealedClientSecret  []byte
}

// The app id/slug + sealed private key, webhook secret, and client secret for in-process use only
// (minting JWTs, verifying webhooks). INTERNAL — the sealed columns are never wired to a handler or
// returned by any RPC.
func (q *Queries) GetSealedGitHubAppConfig(ctx context.Context) (GetSealedGitHubAppConfigRow, error) {
	row := q.db.QueryRow(ctx, getSealedGitHubAppConfig)
	var i GetSealedGitHubAppConfigRow
	err := row.Scan(
		&i.AppID,
		&i.AppSlug,
		&i.ClientID,
		&i.SealedPrivateKey,
		&i.SealedWebhookSecret,
		&i.SealedClientSecret,
	)
	return i, err
}

const upsertGitHubAppConfig = `-- name: UpsertGitHubAppConfig :one
INSERT INTO github_app_config (
    singleton, app_id, app_slug, client_id, sealed_private_key, sealed_webhook_secret, sealed_client_secret, created_by
)
VALUES (true, $1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (singleton) DO UPDATE SET
    app_id = EXCLUDED.app_id,
    app_slug = EXCLUDED.app_slug,
    client_id = EXCLUDED.client_id,
    sealed_private_key = EXCLUDED.sealed_private_key,
    sealed_webhook_secret = EXCLUDED.sealed_webhook_secret,
    sealed_client_secret = EXCLUDED.sealed_client_secret,
    created_by = EXCLUDED.created_by,
    updated_at = now()
RETURNING app_id, app_slug, client_id, created_at, updated_at
`

type UpsertGitHubAppConfigParams struct {
	AppID               string
	AppSlug             string
	ClientID            string
	SealedPrivateKey    []byte
	SealedWebhookSecret []byte
	SealedClientSecret  []byte
	CreatedBy           *string
}

type UpsertGitHubAppConfigRow struct {
	AppID     string
	AppSlug   string
	ClientID  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Create-or-replace the instance's server-wide GitHub App credentials (singleton row). The conflict
// is the success path (re-registering replaces the App), so callers never see AlreadyExists.
// RETURNING yields metadata only — never the sealed key/secret, which are write-only.
func (q *Queries) UpsertGitHubAppConfig(ctx context.Context, arg UpsertGitHubAppConfigParams) (UpsertGitHubAppConfigRow, error) {
	row := q.db.QueryRow(ctx, upsertGitHubAppConfig,
		arg.AppID,
		arg.AppSlug,
		arg.ClientID,
		arg.SealedPrivateKey,
		arg.SealedWebhookSecret,
		arg.SealedClientSecret,
		arg.CreatedBy,
	)
	var i UpsertGitHubAppConfigRow
	err := row.Scan(
		&i.AppID,
		&i.AppSlug,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
