// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type AuditEvent struct {
	ID          string
	WorkspaceID string
	Actor       string
	Action      string
	TargetType  string
	TargetID    string
	CreatedAt   time.Time
}

type Project struct {
	ID          string
	WorkspaceID string
	Name        string
	Slug        string
	CreatedAt   time.Time
}

type User struct {
	ID        string
	Email     string
	CreatedAt time.Time
}

type Workspace struct {
	ID        string
	Name      string
	Slug      string
	CreatedAt time.Time
}

type WorkspaceMember struct {
	WorkspaceID string
	UserID      string
	Role        string
	CreatedAt   time.Time
}
