// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Agent struct {
	ID              string
	ServerID        string
	WorkspaceID     string
	PublicKey       []byte
	CredentialHash  []byte
	AgentVersion    string
	LastSeenAt      *time.Time
	CreatedAt       time.Time
	DockerAvailable *bool
	DockerVersion   string
	Os              string
	Arch            string
}

type AgentRegistrationToken struct {
	ID          string
	ServerID    string
	WorkspaceID string
	TokenHash   []byte
	CreatedBy   string
	CreatedAt   time.Time
	ExpiresAt   time.Time
	ConsumedAt  *time.Time
}

type ApiToken struct {
	ID          string
	UserID      string
	Name        string
	TokenHash   []byte
	TokenPrefix string
	CreatedAt   time.Time
	LastUsedAt  *time.Time
	ExpiresAt   *time.Time
	RevokedAt   *time.Time
}

type AuditEvent struct {
	ID          string
	WorkspaceID *string
	Actor       string
	Action      string
	TargetType  string
	TargetID    string
	CreatedAt   time.Time
}

type Deployment struct {
	ID            string
	EnvironmentID string
	ProjectID     string
	WorkspaceID   string
	ServerID      string
	ImageRef      string
	ContainerPort int32
	HostPort      int32
	ContainerID   string
	Status        string
	Message       string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	SourceKind    string
	SourceAccess  string
	CloneUrl      string
	GitRef        string
	CommitSha     string
	BuiltImageRef string
}

type DeploymentEvent struct {
	ID           string
	DeploymentID string
	Seq          int64
	Kind         string
	Status       string
	Message      string
	CreatedAt    time.Time
}

type EnvVar struct {
	ID            string
	EnvironmentID string
	Key           string
	Value         string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Environment struct {
	ID        string
	ProjectID string
	Name      string
	Slug      string
	Type      string
	CreatedAt time.Time
}

type Invitation struct {
	ID          string
	WorkspaceID string
	Email       string
	Role        string
	TokenHash   []byte
	InvitedBy   string
	CreatedAt   time.Time
	ExpiresAt   time.Time
	AcceptedAt  *time.Time
}

type Project struct {
	ID          string
	WorkspaceID string
	Name        string
	Slug        string
	CreatedAt   time.Time
}

type ProjectSource struct {
	ID            string
	ProjectID     string
	ConnectionID  *string
	Provider      string
	Owner         string
	Repo          string
	FullName      string
	Branch        string
	DefaultBranch string
	IsPrivate     bool
	HtmlUrl       string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Access        string
}

type Secret struct {
	ID            string
	EnvironmentID string
	Key           string
	Ciphertext    []byte
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Server struct {
	ID          string
	WorkspaceID string
	Name        string
	Slug        string
	CreatedAt   time.Time
}

type Session struct {
	ID         string
	UserID     string
	TokenHash  []byte
	UserAgent  string
	CreatedAt  time.Time
	LastUsedAt time.Time
	ExpiresAt  time.Time
	RevokedAt  *time.Time
}

type SourceConnection struct {
	ID                    string
	WorkspaceID           string
	Provider              string
	GithubLogin           string
	GithubUserID          *int64
	AccessTokenCiphertext []byte
	Scopes                string
	ConnectedBy           *string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type User struct {
	ID            string
	Email         string
	CreatedAt     time.Time
	PasswordHash  *string
	EmailVerified bool
}

type UserToken struct {
	ID         string
	UserID     string
	Purpose    string
	TokenHash  []byte
	CreatedAt  time.Time
	ExpiresAt  time.Time
	ConsumedAt *time.Time
}

type Workspace struct {
	ID        string
	Name      string
	Slug      string
	CreatedAt time.Time
}

type WorkspaceMember struct {
	WorkspaceID string
	UserID      string
	Role        string
	CreatedAt   time.Time
}
