// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secrets.sql

package db

import (
	"context"
	"time"
)

const deleteSecret = `-- name: DeleteSecret :one
DELETE FROM secrets
WHERE environment_id = $1 AND key = $2
RETURNING id
`

type DeleteSecretParams struct {
	EnvironmentID string
	Key           string
}

// RETURNING id lets the caller tell a real delete from a no-op (no row -> ErrNoRows
// -> NotFound), so a delete that removed nothing is never audited as a change.
func (q *Queries) DeleteSecret(ctx context.Context, arg DeleteSecretParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteSecret, arg.EnvironmentID, arg.Key)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getEnvironmentWorkspaceID = `-- name: GetEnvironmentWorkspaceID :one
SELECT p.workspace_id
FROM environments e
JOIN projects p ON p.id = e.project_id
WHERE e.id = $1
`

// Resolves an environment's owning workspace through its parent project, so this
// environment-scoped module can authorize and audit against the workspace. (Secrets stay
// environment-scoped; env vars moved to per-service, so this query lives here now.)
func (q *Queries) GetEnvironmentWorkspaceID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getEnvironmentWorkspaceID, id)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const listSecretsByEnvironment = `-- name: ListSecretsByEnvironment :many
SELECT id, environment_id, key, created_at, updated_at
FROM secrets
WHERE environment_id = $1
ORDER BY key
`

type ListSecretsByEnvironmentRow struct {
	ID            string
	EnvironmentID string
	Key           string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Metadata only — keys and timestamps, never the ciphertext (write-only).
func (q *Queries) ListSecretsByEnvironment(ctx context.Context, environmentID string) ([]ListSecretsByEnvironmentRow, error) {
	rows, err := q.db.Query(ctx, listSecretsByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretsByEnvironmentRow{}
	for rows.Next() {
		var i ListSecretsByEnvironmentRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Key,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSecret = `-- name: UpsertSecret :one
INSERT INTO secrets (environment_id, key, ciphertext)
VALUES ($1, $2, $3)
ON CONFLICT (environment_id, key)
DO UPDATE SET ciphertext = EXCLUDED.ciphertext, updated_at = now()
RETURNING id, environment_id, key, created_at, updated_at
`

type UpsertSecretParams struct {
	EnvironmentID string
	Key           string
	Ciphertext    []byte
}

type UpsertSecretRow struct {
	ID            string
	EnvironmentID string
	Key           string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Create-or-update by (environment_id, key). The conflict is the success path
// (secrets are mutable), so callers never see an AlreadyExists error. RETURNING
// yields metadata only — never the ciphertext, which is write-only and leaves the
// database only for a future deploy job, never through the API.
func (q *Queries) UpsertSecret(ctx context.Context, arg UpsertSecretParams) (UpsertSecretRow, error) {
	row := q.db.QueryRow(ctx, upsertSecret, arg.EnvironmentID, arg.Key, arg.Ciphertext)
	var i UpsertSecretRow
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Key,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
