// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: serversetup.sql

package db

import (
	"context"
	"time"
)

const getSSHManagementKey = `-- name: GetSSHManagementKey :one
SELECT id, server_id, fingerprint, public_key, rotation_state, last_used_at, rotated_at, revoked_at, created_by, created_at, updated_at
FROM ssh_management_keys
WHERE server_id = $1
`

type GetSSHManagementKeyRow struct {
	ID            string
	ServerID      string
	Fingerprint   string
	PublicKey     string
	RotationState string
	LastUsedAt    *time.Time
	RotatedAt     *time.Time
	RevokedAt     *time.Time
	CreatedBy     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Metadata only — never the sealed private key, which is write-only.
func (q *Queries) GetSSHManagementKey(ctx context.Context, serverID string) (GetSSHManagementKeyRow, error) {
	row := q.db.QueryRow(ctx, getSSHManagementKey, serverID)
	var i GetSSHManagementKeyRow
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Fingerprint,
		&i.PublicKey,
		&i.RotationState,
		&i.LastUsedAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSealedSSHManagementKey = `-- name: GetSealedSSHManagementKey :one
SELECT sealed_private_key
FROM ssh_management_keys
WHERE server_id = $1 AND revoked_at IS NULL
`

// The sealed private-key ciphertext for an ACTIVE credential. Used ONLY in-process by the
// SSH runner to open the key for a connection — never returned through any RPC.
func (q *Queries) GetSealedSSHManagementKey(ctx context.Context, serverID string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSealedSSHManagementKey, serverID)
	var sealed_private_key []byte
	err := row.Scan(&sealed_private_key)
	return sealed_private_key, err
}

const markSSHManagementKeyUsed = `-- name: MarkSSHManagementKeyUsed :one
UPDATE ssh_management_keys SET
    last_used_at = now(),
    updated_at = now()
WHERE server_id = $1 AND revoked_at IS NULL
RETURNING id
`

// Stamp last_used_at after a successful SSH connection. Returns id so a no-op (absent or
// revoked) is distinguished from a real update.
func (q *Queries) MarkSSHManagementKeyUsed(ctx context.Context, serverID string) (string, error) {
	row := q.db.QueryRow(ctx, markSSHManagementKeyUsed, serverID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const revokeSSHManagementKey = `-- name: RevokeSSHManagementKey :one
UPDATE ssh_management_keys SET
    revoked_at = now(),
    updated_at = now()
WHERE server_id = $1 AND revoked_at IS NULL
RETURNING id
`

// Cut off the management channel: mark the active credential revoked. Returns the row id,
// so a no-op (already revoked / absent) is distinguished from a real revocation and never
// audited as a change.
func (q *Queries) RevokeSSHManagementKey(ctx context.Context, serverID string) (string, error) {
	row := q.db.QueryRow(ctx, revokeSSHManagementKey, serverID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const rotateSSHManagementKey = `-- name: RotateSSHManagementKey :one
UPDATE ssh_management_keys SET
    fingerprint = $2,
    public_key = $3,
    sealed_private_key = $4,
    rotation_state = 'active',
    rotated_at = now(),
    updated_at = now()
WHERE server_id = $1 AND revoked_at IS NULL
RETURNING id, server_id, fingerprint, public_key, rotation_state, last_used_at, rotated_at, revoked_at, created_by, created_at, updated_at
`

type RotateSSHManagementKeyParams struct {
	ServerID         string
	Fingerprint      string
	PublicKey        string
	SealedPrivateKey []byte
}

type RotateSSHManagementKeyRow struct {
	ID            string
	ServerID      string
	Fingerprint   string
	PublicKey     string
	RotationState string
	LastUsedAt    *time.Time
	RotatedAt     *time.Time
	RevokedAt     *time.Time
	CreatedBy     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Replace the key material of a server's ACTIVE credential, stamping rotated_at. No row
// matches a missing or revoked credential, so the caller reports NotFound. RETURNING is
// metadata only.
func (q *Queries) RotateSSHManagementKey(ctx context.Context, arg RotateSSHManagementKeyParams) (RotateSSHManagementKeyRow, error) {
	row := q.db.QueryRow(ctx, rotateSSHManagementKey,
		arg.ServerID,
		arg.Fingerprint,
		arg.PublicKey,
		arg.SealedPrivateKey,
	)
	var i RotateSSHManagementKeyRow
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Fingerprint,
		&i.PublicKey,
		&i.RotationState,
		&i.LastUsedAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSSHManagementKey = `-- name: UpsertSSHManagementKey :one
INSERT INTO ssh_management_keys (server_id, fingerprint, public_key, sealed_private_key, created_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (server_id) DO UPDATE SET
    fingerprint = EXCLUDED.fingerprint,
    public_key = EXCLUDED.public_key,
    sealed_private_key = EXCLUDED.sealed_private_key,
    created_by = EXCLUDED.created_by,
    rotation_state = 'active',
    rotated_at = NULL,
    revoked_at = NULL,
    updated_at = now()
RETURNING id, server_id, fingerprint, public_key, rotation_state, last_used_at, rotated_at, revoked_at, created_by, created_at, updated_at
`

type UpsertSSHManagementKeyParams struct {
	ServerID         string
	Fingerprint      string
	PublicKey        string
	SealedPrivateKey []byte
	CreatedBy        *string
}

type UpsertSSHManagementKeyRow struct {
	ID            string
	ServerID      string
	Fingerprint   string
	PublicKey     string
	RotationState string
	LastUsedAt    *time.Time
	RotatedAt     *time.Time
	RevokedAt     *time.Time
	CreatedBy     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Provision (or re-provision) a server's SSH management credential, replacing any prior
// key material in place and clearing rotation/revocation state. RETURNING yields metadata
// only — never the sealed private key, which is write-only.
func (q *Queries) UpsertSSHManagementKey(ctx context.Context, arg UpsertSSHManagementKeyParams) (UpsertSSHManagementKeyRow, error) {
	row := q.db.QueryRow(ctx, upsertSSHManagementKey,
		arg.ServerID,
		arg.Fingerprint,
		arg.PublicKey,
		arg.SealedPrivateKey,
		arg.CreatedBy,
	)
	var i UpsertSSHManagementKeyRow
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Fingerprint,
		&i.PublicKey,
		&i.RotationState,
		&i.LastUsedAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
