// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package db

import (
	"context"
)

const countServicesByConnection = `-- name: CountServicesByConnection :one
SELECT count(*) FROM services WHERE connection_id = $1
`

// CountServicesByConnection guards DisconnectGitHub: a connection still used by services must
// not be removed. Read by the sources module as a sibling-table read (modules.md Rule 2).
func (q *Queries) CountServicesByConnection(ctx context.Context, connectionID *string) (int64, error) {
	row := q.db.QueryRow(ctx, countServicesByConnection, connectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGitService = `-- name: CreateGitService :one
INSERT INTO services (
    environment_id, project_id, workspace_id, name, slug,
    source_kind, source_access, connection_id, provider, owner, repo, full_name,
    branch, default_branch, is_private, html_url, container_port, visibility
)
VALUES ($1, $2, $3, $4, $5, 'git', $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, environment_id, project_id, workspace_id, name, slug, source_kind, image_ref, template_id, connection_id, provider, owner, repo, full_name, branch, default_branch, is_private, html_url, source_access, container_port, visibility, route_url, created_at, updated_at
`

type CreateGitServiceParams struct {
	EnvironmentID string
	ProjectID     string
	WorkspaceID   string
	Name          string
	Slug          string
	SourceAccess  string
	ConnectionID  *string
	Provider      string
	Owner         string
	Repo          string
	FullName      string
	Branch        string
	DefaultBranch string
	IsPrivate     bool
	HtmlUrl       string
	ContainerPort int32
	Visibility    string
}

// Git service: the source is a repo+ref. connection_id is NULL for a public repo; source_access
// records how it is reached ('public' this slice; 'oauth'/'app' recorded but not yet buildable).
func (q *Queries) CreateGitService(ctx context.Context, arg CreateGitServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createGitService,
		arg.EnvironmentID,
		arg.ProjectID,
		arg.WorkspaceID,
		arg.Name,
		arg.Slug,
		arg.SourceAccess,
		arg.ConnectionID,
		arg.Provider,
		arg.Owner,
		arg.Repo,
		arg.FullName,
		arg.Branch,
		arg.DefaultBranch,
		arg.IsPrivate,
		arg.HtmlUrl,
		arg.ContainerPort,
		arg.Visibility,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.SourceKind,
		&i.ImageRef,
		&i.TemplateID,
		&i.ConnectionID,
		&i.Provider,
		&i.Owner,
		&i.Repo,
		&i.FullName,
		&i.Branch,
		&i.DefaultBranch,
		&i.IsPrivate,
		&i.HtmlUrl,
		&i.SourceAccess,
		&i.ContainerPort,
		&i.Visibility,
		&i.RouteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createService = `-- name: CreateService :one

INSERT INTO services (
    environment_id, project_id, workspace_id, name, slug,
    source_kind, image_ref, template_id, container_port, visibility
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, environment_id, project_id, workspace_id, name, slug, source_kind, image_ref, template_id, connection_id, provider, owner, repo, full_name, branch, default_branch, is_private, html_url, source_access, container_port, visibility, route_url, created_at, updated_at
`

type CreateServiceParams struct {
	EnvironmentID string
	ProjectID     string
	WorkspaceID   string
	Name          string
	Slug          string
	SourceKind    string
	ImageRef      string
	TemplateID    string
	ContainerPort int32
	Visibility    string
}

// A service is a deployable component of a project, living in one environment, owning its
// source (folded onto the row), port, visibility, and deployment history. See
// docs/architecture/deployment-engine.md and modules.md.
// Image or template service: no git columns. workspace_id/project_id are denormalized from
// the environment by the caller (both immutable).
func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.EnvironmentID,
		arg.ProjectID,
		arg.WorkspaceID,
		arg.Name,
		arg.Slug,
		arg.SourceKind,
		arg.ImageRef,
		arg.TemplateID,
		arg.ContainerPort,
		arg.Visibility,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.SourceKind,
		&i.ImageRef,
		&i.TemplateID,
		&i.ConnectionID,
		&i.Provider,
		&i.Owner,
		&i.Repo,
		&i.FullName,
		&i.Branch,
		&i.DefaultBranch,
		&i.IsPrivate,
		&i.HtmlUrl,
		&i.SourceAccess,
		&i.ContainerPort,
		&i.Visibility,
		&i.RouteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :one
DELETE FROM services WHERE id = $1 RETURNING id
`

// RETURNING id distinguishes a real delete from a no-op (no row -> ErrNoRows -> NotFound).
func (q *Queries) DeleteService(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, deleteService, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const getService = `-- name: GetService :one
SELECT id, environment_id, project_id, workspace_id, name, slug, source_kind, image_ref, template_id, connection_id, provider, owner, repo, full_name, branch, default_branch, is_private, html_url, source_access, container_port, visibility, route_url, created_at, updated_at FROM services WHERE id = $1
`

func (q *Queries) GetService(ctx context.Context, id string) (Service, error) {
	row := q.db.QueryRow(ctx, getService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.SourceKind,
		&i.ImageRef,
		&i.TemplateID,
		&i.ConnectionID,
		&i.Provider,
		&i.Owner,
		&i.Repo,
		&i.FullName,
		&i.Branch,
		&i.DefaultBranch,
		&i.IsPrivate,
		&i.HtmlUrl,
		&i.SourceAccess,
		&i.ContainerPort,
		&i.Visibility,
		&i.RouteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceForDeploy = `-- name: GetServiceForDeploy :one
SELECT
    environment_id, project_id, workspace_id, source_kind, image_ref,
    source_access, connection_id, owner, repo, full_name, branch, default_branch, html_url,
    container_port, visibility, slug
FROM services WHERE id = $1
`

type GetServiceForDeployRow struct {
	EnvironmentID string
	ProjectID     string
	WorkspaceID   string
	SourceKind    string
	ImageRef      string
	SourceAccess  string
	ConnectionID  *string
	Owner         string
	Repo          string
	FullName      string
	Branch        string
	DefaultBranch string
	HtmlUrl       string
	ContainerPort int32
	Visibility    string
	Slug          string
}

// GetServiceForDeploy reads the source + routing facts a deployment needs, so the deployments
// module can enqueue a deploy for a service without importing services (a sibling-table read,
// which modules.md Rule 2 permits from a module's postgres.go).
func (q *Queries) GetServiceForDeploy(ctx context.Context, id string) (GetServiceForDeployRow, error) {
	row := q.db.QueryRow(ctx, getServiceForDeploy, id)
	var i GetServiceForDeployRow
	err := row.Scan(
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.SourceKind,
		&i.ImageRef,
		&i.SourceAccess,
		&i.ConnectionID,
		&i.Owner,
		&i.Repo,
		&i.FullName,
		&i.Branch,
		&i.DefaultBranch,
		&i.HtmlUrl,
		&i.ContainerPort,
		&i.Visibility,
		&i.Slug,
	)
	return i, err
}

const getServiceWorkspaceAndProject = `-- name: GetServiceWorkspaceAndProject :one
SELECT workspace_id, project_id FROM services WHERE id = $1
`

type GetServiceWorkspaceAndProjectRow struct {
	WorkspaceID string
	ProjectID   string
}

// GetServiceWorkspaceAndProject resolves a service's owning workspace and project (both
// denormalized onto the row) for authorization and scoping.
func (q *Queries) GetServiceWorkspaceAndProject(ctx context.Context, id string) (GetServiceWorkspaceAndProjectRow, error) {
	row := q.db.QueryRow(ctx, getServiceWorkspaceAndProject, id)
	var i GetServiceWorkspaceAndProjectRow
	err := row.Scan(&i.WorkspaceID, &i.ProjectID)
	return i, err
}

const listServicesByEnvironment = `-- name: ListServicesByEnvironment :many
SELECT id, environment_id, project_id, workspace_id, name, slug, source_kind, image_ref, template_id, connection_id, provider, owner, repo, full_name, branch, default_branch, is_private, html_url, source_access, container_port, visibility, route_url, created_at, updated_at FROM services WHERE environment_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListServicesByEnvironment(ctx context.Context, environmentID string) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.Name,
			&i.Slug,
			&i.SourceKind,
			&i.ImageRef,
			&i.TemplateID,
			&i.ConnectionID,
			&i.Provider,
			&i.Owner,
			&i.Repo,
			&i.FullName,
			&i.Branch,
			&i.DefaultBranch,
			&i.IsPrivate,
			&i.HtmlUrl,
			&i.SourceAccess,
			&i.ContainerPort,
			&i.Visibility,
			&i.RouteUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByProject = `-- name: ListServicesByProject :many
SELECT id, environment_id, project_id, workspace_id, name, slug, source_kind, image_ref, template_id, connection_id, provider, owner, repo, full_name, branch, default_branch, is_private, html_url, source_access, container_port, visibility, route_url, created_at, updated_at FROM services WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListServicesByProject(ctx context.Context, projectID string) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.Name,
			&i.Slug,
			&i.SourceKind,
			&i.ImageRef,
			&i.TemplateID,
			&i.ConnectionID,
			&i.Provider,
			&i.Owner,
			&i.Repo,
			&i.FullName,
			&i.Branch,
			&i.DefaultBranch,
			&i.IsPrivate,
			&i.HtmlUrl,
			&i.SourceAccess,
			&i.ContainerPort,
			&i.Visibility,
			&i.RouteUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByWorkspace = `-- name: ListServicesByWorkspace :many
SELECT id, environment_id, project_id, workspace_id, name, slug, source_kind, image_ref, template_id, connection_id, provider, owner, repo, full_name, branch, default_branch, is_private, html_url, source_access, container_port, visibility, route_url, created_at, updated_at FROM services WHERE workspace_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListServicesByWorkspace(ctx context.Context, workspaceID string) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.Name,
			&i.Slug,
			&i.SourceKind,
			&i.ImageRef,
			&i.TemplateID,
			&i.ConnectionID,
			&i.Provider,
			&i.Owner,
			&i.Repo,
			&i.FullName,
			&i.Branch,
			&i.DefaultBranch,
			&i.IsPrivate,
			&i.HtmlUrl,
			&i.SourceAccess,
			&i.ContainerPort,
			&i.Visibility,
			&i.RouteUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServiceRouteURL = `-- name: UpdateServiceRouteURL :exec
UPDATE services SET route_url = $2, updated_at = now() WHERE id = $1
`

type UpdateServiceRouteURLParams struct {
	ID       string
	RouteUrl string
}

// UpdateServiceRouteURL keeps the service's cached public URL current from the latest running
// deployment's reported route. Only called for a public service with a real route.
func (q *Queries) UpdateServiceRouteURL(ctx context.Context, arg UpdateServiceRouteURLParams) error {
	_, err := q.db.Exec(ctx, updateServiceRouteURL, arg.ID, arg.RouteUrl)
	return err
}

const updateServiceSource = `-- name: UpdateServiceSource :one
UPDATE services
SET source_kind = $2, image_ref = $3, template_id = $4, connection_id = $5,
    provider = $6, owner = $7, repo = $8, full_name = $9, branch = $10,
    default_branch = $11, is_private = $12, html_url = $13, source_access = $14,
    container_port = $15, updated_at = now()
WHERE id = $1
RETURNING id, environment_id, project_id, workspace_id, name, slug, source_kind, image_ref, template_id, connection_id, provider, owner, repo, full_name, branch, default_branch, is_private, html_url, source_access, container_port, visibility, route_url, created_at, updated_at
`

type UpdateServiceSourceParams struct {
	ID            string
	SourceKind    string
	ImageRef      string
	TemplateID    string
	ConnectionID  *string
	Provider      string
	Owner         string
	Repo          string
	FullName      string
	Branch        string
	DefaultBranch string
	IsPrivate     bool
	HtmlUrl       string
	SourceAccess  string
	ContainerPort int32
}

// Reconnect/change a service's source (and port). Updates every source-related column so a
// service can switch kind (image<->git<->template).
func (q *Queries) UpdateServiceSource(ctx context.Context, arg UpdateServiceSourceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateServiceSource,
		arg.ID,
		arg.SourceKind,
		arg.ImageRef,
		arg.TemplateID,
		arg.ConnectionID,
		arg.Provider,
		arg.Owner,
		arg.Repo,
		arg.FullName,
		arg.Branch,
		arg.DefaultBranch,
		arg.IsPrivate,
		arg.HtmlUrl,
		arg.SourceAccess,
		arg.ContainerPort,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.SourceKind,
		&i.ImageRef,
		&i.TemplateID,
		&i.ConnectionID,
		&i.Provider,
		&i.Owner,
		&i.Repo,
		&i.FullName,
		&i.Branch,
		&i.DefaultBranch,
		&i.IsPrivate,
		&i.HtmlUrl,
		&i.SourceAccess,
		&i.ContainerPort,
		&i.Visibility,
		&i.RouteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateServiceVisibility = `-- name: UpdateServiceVisibility :one
UPDATE services SET visibility = $2, updated_at = now() WHERE id = $1 RETURNING id, environment_id, project_id, workspace_id, name, slug, source_kind, image_ref, template_id, connection_id, provider, owner, repo, full_name, branch, default_branch, is_private, html_url, source_access, container_port, visibility, route_url, created_at, updated_at
`

type UpdateServiceVisibilityParams struct {
	ID         string
	Visibility string
}

func (q *Queries) UpdateServiceVisibility(ctx context.Context, arg UpdateServiceVisibilityParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateServiceVisibility, arg.ID, arg.Visibility)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.SourceKind,
		&i.ImageRef,
		&i.TemplateID,
		&i.ConnectionID,
		&i.Provider,
		&i.Owner,
		&i.Repo,
		&i.FullName,
		&i.Branch,
		&i.DefaultBranch,
		&i.IsPrivate,
		&i.HtmlUrl,
		&i.SourceAccess,
		&i.ContainerPort,
		&i.Visibility,
		&i.RouteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
