// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: servers.sql

package db

import (
	"context"
)

const createServer = `-- name: CreateServer :one
INSERT INTO servers (workspace_id, name, slug)
VALUES ($1, $2, $3)
RETURNING id, workspace_id, name, slug, created_at
`

type CreateServerParams struct {
	WorkspaceID string
	Name        string
	Slug        string
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, createServer, arg.WorkspaceID, arg.Name, arg.Slug)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const deleteServer = `-- name: DeleteServer :one
DELETE FROM servers
WHERE id = $1
RETURNING id
`

// DeleteServer removes the server (agents, registration tokens, and deployments
// cascade). RETURNING id lets the caller tell a real delete from a no-op, so a delete
// that removed nothing is never audited as a change (cf. DeleteEnvVar).
func (q *Queries) DeleteServer(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, deleteServer, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const getServer = `-- name: GetServer :one
SELECT id, workspace_id, name, slug, created_at
FROM servers
WHERE id = $1
`

func (q *Queries) GetServer(ctx context.Context, id string) (Server, error) {
	row := q.db.QueryRow(ctx, getServer, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const listServersByWorkspace = `-- name: ListServersByWorkspace :many
SELECT id, workspace_id, name, slug, created_at
FROM servers
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListServersByWorkspace(ctx context.Context, workspaceID string) ([]Server, error) {
	rows, err := q.db.Query(ctx, listServersByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Server{}
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
