// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package db

import (
	"context"
	"time"
)

const countProjectSourcesByConnection = `-- name: CountProjectSourcesByConnection :one
SELECT count(*) FROM project_sources WHERE connection_id = $1
`

// Guards DisconnectGitHub: a connection still in use by projects must not be removed.
func (q *Queries) CountProjectSourcesByConnection(ctx context.Context, connectionID *string) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectSourcesByConnection, connectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteProjectSource = `-- name: DeleteProjectSource :one
DELETE FROM project_sources
WHERE project_id = $1
RETURNING id
`

// RETURNING id distinguishes a real delete from a no-op (NotFound).
func (q *Queries) DeleteProjectSource(ctx context.Context, projectID string) (string, error) {
	row := q.db.QueryRow(ctx, deleteProjectSource, projectID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteSourceConnection = `-- name: DeleteSourceConnection :one
DELETE FROM source_connections
WHERE workspace_id = $1 AND provider = $2
RETURNING id
`

type DeleteSourceConnectionParams struct {
	WorkspaceID string
	Provider    string
}

// RETURNING id distinguishes a real delete from a no-op (no row -> ErrNoRows ->
// NotFound), so a delete that removed nothing is never audited as a change.
func (q *Queries) DeleteSourceConnection(ctx context.Context, arg DeleteSourceConnectionParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteSourceConnection, arg.WorkspaceID, arg.Provider)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getConnectionTokenByWorkspace = `-- name: GetConnectionTokenByWorkspace :one
SELECT access_token_ciphertext
FROM source_connections
WHERE workspace_id = $1 AND provider = $2
`

type GetConnectionTokenByWorkspaceParams struct {
	WorkspaceID string
	Provider    string
}

// Returns the sealed token for server-side provider calls. INTERNAL — the ciphertext
// is never wired to a handler or returned by any RPC.
func (q *Queries) GetConnectionTokenByWorkspace(ctx context.Context, arg GetConnectionTokenByWorkspaceParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getConnectionTokenByWorkspace, arg.WorkspaceID, arg.Provider)
	var access_token_ciphertext []byte
	err := row.Scan(&access_token_ciphertext)
	return access_token_ciphertext, err
}

const getProjectSource = `-- name: GetProjectSource :one
SELECT
    ps.id, ps.project_id, ps.connection_id, ps.provider, ps.owner, ps.repo, ps.full_name,
    ps.branch, ps.default_branch, ps.is_private, ps.html_url, ps.access, ps.created_at, ps.updated_at,
    sc.github_login
FROM project_sources ps
LEFT JOIN source_connections sc ON sc.id = ps.connection_id
WHERE ps.project_id = $1
`

type GetProjectSourceRow struct {
	ID            string
	ProjectID     string
	ConnectionID  *string
	Provider      string
	Owner         string
	Repo          string
	FullName      string
	Branch        string
	DefaultBranch string
	IsPrivate     bool
	HtmlUrl       string
	Access        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	GithubLogin   *string
}

// LEFT JOIN the connection for the account login (display): a public source has no
// connection, so github_login is NULL there. Workspace resolution for authorization uses
// the shared GetProjectWorkspaceID.
func (q *Queries) GetProjectSource(ctx context.Context, projectID string) (GetProjectSourceRow, error) {
	row := q.db.QueryRow(ctx, getProjectSource, projectID)
	var i GetProjectSourceRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ConnectionID,
		&i.Provider,
		&i.Owner,
		&i.Repo,
		&i.FullName,
		&i.Branch,
		&i.DefaultBranch,
		&i.IsPrivate,
		&i.HtmlUrl,
		&i.Access,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubLogin,
	)
	return i, err
}

const getSourceConnectionByWorkspace = `-- name: GetSourceConnectionByWorkspace :one
SELECT id, workspace_id, provider, github_login, github_user_id, scopes, connected_by, created_at, updated_at
FROM source_connections
WHERE workspace_id = $1 AND provider = $2
`

type GetSourceConnectionByWorkspaceParams struct {
	WorkspaceID string
	Provider    string
}

type GetSourceConnectionByWorkspaceRow struct {
	ID           string
	WorkspaceID  string
	Provider     string
	GithubLogin  string
	GithubUserID *int64
	Scopes       string
	ConnectedBy  *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// Metadata only — never the access token (write-only).
func (q *Queries) GetSourceConnectionByWorkspace(ctx context.Context, arg GetSourceConnectionByWorkspaceParams) (GetSourceConnectionByWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, getSourceConnectionByWorkspace, arg.WorkspaceID, arg.Provider)
	var i GetSourceConnectionByWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.GithubLogin,
		&i.GithubUserID,
		&i.Scopes,
		&i.ConnectedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectSourcesByWorkspace = `-- name: ListProjectSourcesByWorkspace :many
SELECT
    ps.id, ps.project_id, ps.connection_id, ps.provider, ps.owner, ps.repo, ps.full_name,
    ps.branch, ps.default_branch, ps.is_private, ps.html_url, ps.access, ps.created_at, ps.updated_at,
    sc.github_login
FROM project_sources ps
LEFT JOIN source_connections sc ON sc.id = ps.connection_id
JOIN projects p ON p.id = ps.project_id
WHERE p.workspace_id = $1
ORDER BY ps.updated_at DESC
`

type ListProjectSourcesByWorkspaceRow struct {
	ID            string
	ProjectID     string
	ConnectionID  *string
	Provider      string
	Owner         string
	Repo          string
	FullName      string
	Branch        string
	DefaultBranch string
	IsPrivate     bool
	HtmlUrl       string
	Access        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	GithubLogin   *string
}

// Batch read for the projects grid (avoids an N+1 over GetProjectSource). Joins the
// parent project to scope by workspace and LEFT JOINs the connection for the account
// login (NULL for a public source, which has no connection).
func (q *Queries) ListProjectSourcesByWorkspace(ctx context.Context, workspaceID string) ([]ListProjectSourcesByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listProjectSourcesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectSourcesByWorkspaceRow{}
	for rows.Next() {
		var i ListProjectSourcesByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ConnectionID,
			&i.Provider,
			&i.Owner,
			&i.Repo,
			&i.FullName,
			&i.Branch,
			&i.DefaultBranch,
			&i.IsPrivate,
			&i.HtmlUrl,
			&i.Access,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GithubLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProjectSource = `-- name: UpsertProjectSource :one
INSERT INTO project_sources (
    project_id, connection_id, provider, owner, repo, full_name, branch, default_branch, is_private, html_url, access
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (project_id)
DO UPDATE SET
    connection_id = EXCLUDED.connection_id,
    provider = EXCLUDED.provider,
    owner = EXCLUDED.owner,
    repo = EXCLUDED.repo,
    full_name = EXCLUDED.full_name,
    branch = EXCLUDED.branch,
    default_branch = EXCLUDED.default_branch,
    is_private = EXCLUDED.is_private,
    html_url = EXCLUDED.html_url,
    access = EXCLUDED.access,
    updated_at = now()
RETURNING id, project_id, connection_id, provider, owner, repo, full_name, branch, default_branch, is_private, html_url, access, created_at, updated_at
`

type UpsertProjectSourceParams struct {
	ProjectID     string
	ConnectionID  *string
	Provider      string
	Owner         string
	Repo          string
	FullName      string
	Branch        string
	DefaultBranch string
	IsPrivate     bool
	HtmlUrl       string
	Access        string
}

type UpsertProjectSourceRow struct {
	ID            string
	ProjectID     string
	ConnectionID  *string
	Provider      string
	Owner         string
	Repo          string
	FullName      string
	Branch        string
	DefaultBranch string
	IsPrivate     bool
	HtmlUrl       string
	Access        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Create-or-update by project_id (one source per project). The conflict is the success
// path (reconnecting a project to a different repo or branch). connection_id is NULL for
// a public source; `access` records how the source is reached ('oauth'|'public'|'app').
func (q *Queries) UpsertProjectSource(ctx context.Context, arg UpsertProjectSourceParams) (UpsertProjectSourceRow, error) {
	row := q.db.QueryRow(ctx, upsertProjectSource,
		arg.ProjectID,
		arg.ConnectionID,
		arg.Provider,
		arg.Owner,
		arg.Repo,
		arg.FullName,
		arg.Branch,
		arg.DefaultBranch,
		arg.IsPrivate,
		arg.HtmlUrl,
		arg.Access,
	)
	var i UpsertProjectSourceRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ConnectionID,
		&i.Provider,
		&i.Owner,
		&i.Repo,
		&i.FullName,
		&i.Branch,
		&i.DefaultBranch,
		&i.IsPrivate,
		&i.HtmlUrl,
		&i.Access,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSourceConnection = `-- name: UpsertSourceConnection :one
INSERT INTO source_connections (
    workspace_id, provider, github_login, github_user_id, access_token_ciphertext, scopes, connected_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (workspace_id, provider)
DO UPDATE SET
    github_login = EXCLUDED.github_login,
    github_user_id = EXCLUDED.github_user_id,
    access_token_ciphertext = EXCLUDED.access_token_ciphertext,
    scopes = EXCLUDED.scopes,
    connected_by = EXCLUDED.connected_by,
    updated_at = now()
RETURNING id, workspace_id, provider, github_login, github_user_id, scopes, connected_by, created_at, updated_at
`

type UpsertSourceConnectionParams struct {
	WorkspaceID           string
	Provider              string
	GithubLogin           string
	GithubUserID          *int64
	AccessTokenCiphertext []byte
	Scopes                string
	ConnectedBy           *string
}

type UpsertSourceConnectionRow struct {
	ID           string
	WorkspaceID  string
	Provider     string
	GithubLogin  string
	GithubUserID *int64
	Scopes       string
	ConnectedBy  *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// Create-or-update the workspace's provider connection (one per workspace + provider).
// The conflict is the success path (reconnecting refreshes the token and identity), so
// callers never see AlreadyExists. RETURNING yields metadata only — never the token,
// which is write-only and leaves the database only to call the provider server-side.
func (q *Queries) UpsertSourceConnection(ctx context.Context, arg UpsertSourceConnectionParams) (UpsertSourceConnectionRow, error) {
	row := q.db.QueryRow(ctx, upsertSourceConnection,
		arg.WorkspaceID,
		arg.Provider,
		arg.GithubLogin,
		arg.GithubUserID,
		arg.AccessTokenCiphertext,
		arg.Scopes,
		arg.ConnectedBy,
	)
	var i UpsertSourceConnectionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.GithubLogin,
		&i.GithubUserID,
		&i.Scopes,
		&i.ConnectedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
