// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package db

import (
	"context"
	"time"
)

const deleteConnectionByID = `-- name: DeleteConnectionByID :one
DELETE FROM source_connections
WHERE id = $1
RETURNING id
`

// RETURNING id distinguishes a real delete from a no-op (no row -> ErrNoRows -> NotFound), so a
// delete that removed nothing is never audited as a change.
func (q *Queries) DeleteConnectionByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, deleteConnectionByID, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const getConnectionByID = `-- name: GetConnectionByID :one
SELECT id, workspace_id, provider, kind, account_login, account_id, installation_id, scopes, connected_by, created_at, updated_at
FROM source_connections
WHERE id = $1
`

type GetConnectionByIDRow struct {
	ID             string
	WorkspaceID    string
	Provider       string
	Kind           string
	AccountLogin   string
	AccountID      *int64
	InstallationID *string
	Scopes         string
	ConnectedBy    *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// One integration's metadata by id (to authorize via its workspace + display it). Never the token.
func (q *Queries) GetConnectionByID(ctx context.Context, id string) (GetConnectionByIDRow, error) {
	row := q.db.QueryRow(ctx, getConnectionByID, id)
	var i GetConnectionByIDRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.Kind,
		&i.AccountLogin,
		&i.AccountID,
		&i.InstallationID,
		&i.Scopes,
		&i.ConnectedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstallationByConnection = `-- name: GetInstallationByConnection :one
SELECT installation_id
FROM source_connections
WHERE id = $1
`

// The App installation id for one connection, to mint a per-installation token. INTERNAL — the id
// resolves a token that is never returned by an RPC.
func (q *Queries) GetInstallationByConnection(ctx context.Context, id string) (*string, error) {
	row := q.db.QueryRow(ctx, getInstallationByConnection, id)
	var installation_id *string
	err := row.Scan(&installation_id)
	return installation_id, err
}

const getSealedTokenByConnection = `-- name: GetSealedTokenByConnection :one
SELECT access_token_ciphertext
FROM source_connections
WHERE id = $1
`

// The sealed OAuth token for one connection, for server-side provider calls. INTERNAL — the
// ciphertext is never wired to a handler or returned by any RPC.
func (q *Queries) GetSealedTokenByConnection(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSealedTokenByConnection, id)
	var access_token_ciphertext []byte
	err := row.Scan(&access_token_ciphertext)
	return access_token_ciphertext, err
}

const insertAppConnection = `-- name: InsertAppConnection :one
INSERT INTO source_connections (
    workspace_id, provider, kind, account_login, account_id, installation_id, connected_by
)
VALUES ($1, $2, 'app', $3, $4, $5, $6)
ON CONFLICT (provider, installation_id) WHERE installation_id IS NOT NULL
DO UPDATE SET
    workspace_id = EXCLUDED.workspace_id,
    account_login = EXCLUDED.account_login,
    account_id = EXCLUDED.account_id,
    connected_by = EXCLUDED.connected_by,
    updated_at = now()
RETURNING id, workspace_id, provider, kind, account_login, account_id, installation_id, scopes, connected_by, created_at, updated_at
`

type InsertAppConnectionParams struct {
	WorkspaceID    string
	Provider       string
	AccountLogin   string
	AccountID      *int64
	InstallationID *string
	ConnectedBy    *string
}

type InsertAppConnectionRow struct {
	ID             string
	WorkspaceID    string
	Provider       string
	Kind           string
	AccountLogin   string
	AccountID      *int64
	InstallationID *string
	Scopes         string
	ConnectedBy    *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// Create-or-refresh an App-installation integration. The installation id is globally unique, so a
// re-install of the same installation refreshes the existing row (and re-homes it to this workspace)
// via the partial unique index. RETURNING is metadata only.
func (q *Queries) InsertAppConnection(ctx context.Context, arg InsertAppConnectionParams) (InsertAppConnectionRow, error) {
	row := q.db.QueryRow(ctx, insertAppConnection,
		arg.WorkspaceID,
		arg.Provider,
		arg.AccountLogin,
		arg.AccountID,
		arg.InstallationID,
		arg.ConnectedBy,
	)
	var i InsertAppConnectionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.Kind,
		&i.AccountLogin,
		&i.AccountID,
		&i.InstallationID,
		&i.Scopes,
		&i.ConnectedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOAuthConnection = `-- name: InsertOAuthConnection :one
INSERT INTO source_connections (
    workspace_id, provider, kind, account_login, account_id, access_token_ciphertext, scopes, connected_by
)
VALUES ($1, $2, 'oauth', $3, $4, $5, $6, $7)
ON CONFLICT (workspace_id, provider, kind, account_id) WHERE account_id IS NOT NULL
DO UPDATE SET
    account_login = EXCLUDED.account_login,
    access_token_ciphertext = EXCLUDED.access_token_ciphertext,
    scopes = EXCLUDED.scopes,
    connected_by = EXCLUDED.connected_by,
    updated_at = now()
RETURNING id, workspace_id, provider, kind, account_login, account_id, installation_id, scopes, connected_by, created_at, updated_at
`

type InsertOAuthConnectionParams struct {
	WorkspaceID           string
	Provider              string
	AccountLogin          string
	AccountID             *int64
	AccessTokenCiphertext []byte
	Scopes                string
	ConnectedBy           *string
}

type InsertOAuthConnectionRow struct {
	ID             string
	WorkspaceID    string
	Provider       string
	Kind           string
	AccountLogin   string
	AccountID      *int64
	InstallationID *string
	Scopes         string
	ConnectedBy    *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// Create-or-refresh an OAuth integration. Reconnecting the SAME account (workspace+provider+kind+
// account_id) refreshes the row via the partial unique index, so callers never see AlreadyExists; a
// different account adds another integration. RETURNING is metadata only — never the token.
func (q *Queries) InsertOAuthConnection(ctx context.Context, arg InsertOAuthConnectionParams) (InsertOAuthConnectionRow, error) {
	row := q.db.QueryRow(ctx, insertOAuthConnection,
		arg.WorkspaceID,
		arg.Provider,
		arg.AccountLogin,
		arg.AccountID,
		arg.AccessTokenCiphertext,
		arg.Scopes,
		arg.ConnectedBy,
	)
	var i InsertOAuthConnectionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.Kind,
		&i.AccountLogin,
		&i.AccountID,
		&i.InstallationID,
		&i.Scopes,
		&i.ConnectedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConnectionsByWorkspace = `-- name: ListConnectionsByWorkspace :many
SELECT id, workspace_id, provider, kind, account_login, account_id, installation_id, scopes, connected_by, created_at, updated_at
FROM source_connections
WHERE workspace_id = $1
ORDER BY created_at DESC
`

type ListConnectionsByWorkspaceRow struct {
	ID             string
	WorkspaceID    string
	Provider       string
	Kind           string
	AccountLogin   string
	AccountID      *int64
	InstallationID *string
	Scopes         string
	ConnectedBy    *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// All integrations (connections) for a workspace, newest first. Metadata only — never the sealed
// token, which is write-only and leaves the database only to call the provider server-side.
func (q *Queries) ListConnectionsByWorkspace(ctx context.Context, workspaceID string) ([]ListConnectionsByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listConnectionsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConnectionsByWorkspaceRow{}
	for rows.Next() {
		var i ListConnectionsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Provider,
			&i.Kind,
			&i.AccountLogin,
			&i.AccountID,
			&i.InstallationID,
			&i.Scopes,
			&i.ConnectedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
