// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package db

import (
	"context"
	"time"
)

const deleteSourceConnection = `-- name: DeleteSourceConnection :one
DELETE FROM source_connections
WHERE workspace_id = $1 AND provider = $2
RETURNING id
`

type DeleteSourceConnectionParams struct {
	WorkspaceID string
	Provider    string
}

// RETURNING id distinguishes a real delete from a no-op (no row -> ErrNoRows ->
// NotFound), so a delete that removed nothing is never audited as a change.
func (q *Queries) DeleteSourceConnection(ctx context.Context, arg DeleteSourceConnectionParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteSourceConnection, arg.WorkspaceID, arg.Provider)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getConnectionTokenByWorkspace = `-- name: GetConnectionTokenByWorkspace :one
SELECT access_token_ciphertext
FROM source_connections
WHERE workspace_id = $1 AND provider = $2
`

type GetConnectionTokenByWorkspaceParams struct {
	WorkspaceID string
	Provider    string
}

// Returns the sealed token for server-side provider calls. INTERNAL — the ciphertext
// is never wired to a handler or returned by any RPC.
func (q *Queries) GetConnectionTokenByWorkspace(ctx context.Context, arg GetConnectionTokenByWorkspaceParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getConnectionTokenByWorkspace, arg.WorkspaceID, arg.Provider)
	var access_token_ciphertext []byte
	err := row.Scan(&access_token_ciphertext)
	return access_token_ciphertext, err
}

const getSourceConnectionByWorkspace = `-- name: GetSourceConnectionByWorkspace :one
SELECT id, workspace_id, provider, github_login, github_user_id, scopes, connected_by, created_at, updated_at
FROM source_connections
WHERE workspace_id = $1 AND provider = $2
`

type GetSourceConnectionByWorkspaceParams struct {
	WorkspaceID string
	Provider    string
}

type GetSourceConnectionByWorkspaceRow struct {
	ID           string
	WorkspaceID  string
	Provider     string
	GithubLogin  string
	GithubUserID *int64
	Scopes       string
	ConnectedBy  *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// Metadata only — never the access token (write-only).
func (q *Queries) GetSourceConnectionByWorkspace(ctx context.Context, arg GetSourceConnectionByWorkspaceParams) (GetSourceConnectionByWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, getSourceConnectionByWorkspace, arg.WorkspaceID, arg.Provider)
	var i GetSourceConnectionByWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.GithubLogin,
		&i.GithubUserID,
		&i.Scopes,
		&i.ConnectedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSourceConnection = `-- name: UpsertSourceConnection :one
INSERT INTO source_connections (
    workspace_id, provider, github_login, github_user_id, access_token_ciphertext, scopes, connected_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (workspace_id, provider)
DO UPDATE SET
    github_login = EXCLUDED.github_login,
    github_user_id = EXCLUDED.github_user_id,
    access_token_ciphertext = EXCLUDED.access_token_ciphertext,
    scopes = EXCLUDED.scopes,
    connected_by = EXCLUDED.connected_by,
    updated_at = now()
RETURNING id, workspace_id, provider, github_login, github_user_id, scopes, connected_by, created_at, updated_at
`

type UpsertSourceConnectionParams struct {
	WorkspaceID           string
	Provider              string
	GithubLogin           string
	GithubUserID          *int64
	AccessTokenCiphertext []byte
	Scopes                string
	ConnectedBy           *string
}

type UpsertSourceConnectionRow struct {
	ID           string
	WorkspaceID  string
	Provider     string
	GithubLogin  string
	GithubUserID *int64
	Scopes       string
	ConnectedBy  *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// Create-or-update the workspace's provider connection (one per workspace + provider).
// The conflict is the success path (reconnecting refreshes the token and identity), so
// callers never see AlreadyExists. RETURNING yields metadata only — never the token,
// which is write-only and leaves the database only to call the provider server-side.
func (q *Queries) UpsertSourceConnection(ctx context.Context, arg UpsertSourceConnectionParams) (UpsertSourceConnectionRow, error) {
	row := q.db.QueryRow(ctx, upsertSourceConnection,
		arg.WorkspaceID,
		arg.Provider,
		arg.GithubLogin,
		arg.GithubUserID,
		arg.AccessTokenCiphertext,
		arg.Scopes,
		arg.ConnectedBy,
	)
	var i UpsertSourceConnectionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.GithubLogin,
		&i.GithubUserID,
		&i.Scopes,
		&i.ConnectedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
