// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package db

import (
	"context"
)

const getWorkspaceByInstallation = `-- name: GetWorkspaceByInstallation :one

SELECT workspace_id FROM source_connections
WHERE provider = 'github_app' AND installation_id = $1
`

// Queries for the webhooks module (internal/webhooks). It maps a GitHub webhook's installation +
// repo to the workspace's matching git services, reading source_connections + services as
// sibling-table reads (modules.md Rule 2 permits this from a module's postgres.go).
// Resolve a GitHub App installation id to its workspace, so a webhook delivery is scoped to the
// workspace that connected the installation. ErrNoRows for an unknown/unconnected installation.
func (q *Queries) GetWorkspaceByInstallation(ctx context.Context, installationID *string) (string, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByInstallation, installationID)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const listServiceIDsForRepo = `-- name: ListServiceIDsForRepo :many
SELECT id FROM services
WHERE workspace_id = $1
  AND source_kind = 'git'
  AND lower(owner) = lower($2)
  AND lower(repo) = lower($3)
`

type ListServiceIDsForRepoParams struct {
	WorkspaceID string
	Lower       string
	Lower_2     string
}

// The git services in a workspace whose source is owner/repo (case-insensitive), so a PR event maps
// to the service(s) to preview. A repo may back more than one service.
func (q *Queries) ListServiceIDsForRepo(ctx context.Context, arg ListServiceIDsForRepoParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listServiceIDsForRepo, arg.WorkspaceID, arg.Lower, arg.Lower_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
